### ISSUE TITLE
Recording doesn't capture jumping both hands to a number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#386] opened 2021-05-04 16:12 UTC
For https://github.com/phetsims/QA/issues/647. Seen on Win 10 Chrome and MacOS 11 Safari.

When recording (this test used metacog recording) the record wrapper does not pick up when keyboard commands are used to jump both hands to a specific number.

**Comment by zepumph** [comment] 2021-05-04 19:08
I can debug this better now using https://github.com/phetsims/phet-io-wrappers/issues/415

**Comment by zepumph** [comment] 2021-05-05 00:59
This is likely a subset https://github.com/phetsims/phet-io/issues/1748

**Comment by zepumph** [comment] 2021-05-05 18:00
This is not an issue with recording, as I confirmed that the recorded events look good. It seems to be an issue with our playback strategy, on hold by https://github.com/phetsims/phet-io/issues/1748 and not blocking RaP data collection this week.

**Comment by zepumph** [comment] 2021-05-05 18:02
I confirmed this with the following steps:

1. load the record wrapper with `?localFile`
2. type in console `const _ = document.getElementById( 'sim').contentWindow._`
3. naviagate to both hands, and press a number key
4. type `window.phetio.eventArray.filter( function filte(x){ return x.phetioID.includes( 'tupleProperty') || (x.children && _.some( x.children, filte))});` in the console. You will see the event from which the tupleProperty changed from the default values to both being the number you pressed.

**Comment by zepumph** [comment] 2022-08-19 16:51
We don't support the playback wrapper anymore, so I'm going to close this. I just re-confirmed this is working in the input-record-and-playback wrapper.

**Closed by zepumph** 2022-08-19 16:51 UTC
Labels: type:bug, dev:phet-io, dev:alt-input
