### ISSUE TITLE
Tension between position regions and in-proportion tolerance

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#439] opened 2022-03-02 17:13 UTC
This has come up a few times now, in https://github.com/phetsims/ratio-and-proportion/issues/437, as well as number (2) in https://github.com/phetsims/ratio-and-proportion/issues/421#issuecomment-1057166863. The basic issue is that we "hollywooded" the in proportion state to be a region with tolerance. This makes the sim actually usable, but we didn't apply the same behavior to the position regions, which allows for a description to say you are "around 4th tick mark" when you are in-proportion, and the math suggests that in-proportion is having the hand actually ON the 4th tick mark. 

The solution to the problem is to know about all hollywooded features of the sim early in the design process, and reflect that in the model (when possible), such that all views (description/sound/visual/voicing) can utilitize the same information to convey the data to the user.

@terracoda and I spoke at length about this on Friday, and more today. We primarily feel like it is something we want to note, reflect on and fix in future sims (like quad), but going back and adjusting RAP likely isn't in the cards. 

@terracoda feel free to edit inline, or add your thoughts to this. We may just close this if we can't think of steps that are able to be done for RAP before its fast-approaching feature-completion deadline. Tagging @emily-phet, as well as @BLFiedler and @jessegreenberg (quad team) to note this challenge we are having with the voicing in RAP.

**Comment by terracoda** [comment] 2022-03-02 18:06
Just noting that I can get the incorrect region "Extremely close to right hand, almost on third Tick Mark." even at end of drag. It might depend how fast I am moving with the mouse, but it is pretty easy to re-produce.

I am kind of concerned about this issue.

I wonder if a simple removal of those "almost on" regions during active dragging would work.
For example, if am actively dragging near a tick mark I only ever get distance-progress no rough tick-mark-region, and then I only get tick-mark-region at end of drag once the hand snaps to the tick mark.

Marking this to discuss very briefly on Friday. We still have lots to do to implement Voicing for this sim.

**Comment by zepumph** [comment] 2022-03-02 18:25
>Just noting that I can get the incorrect region "Extremely close to right hand, almost on third Tick Mark." even at end of drag. It might depend how fast I am moving with the mouse, but it is pretty easy to re-produce.

Can you please create a new issue here. I want to know if we can get a region that says "almost on" when we are snapping to "on". That is a bug, and not part of this design-related issue.

**Comment by terracoda** [comment] 2022-03-04 20:14
**Miss-placed Comments from #437**
And I think #421 is a related issue to #437, but we can't easily solve that one, since there are potentially 30 or more edge cases when the range of tick marks is set to 30.

I wonder if it might be necessary to silence the regions near the tick marks for Voicing. We can think about that here and in #434.

For the record, I don't think the in-between-tick-mark regions proposed in #434 will address the issue. The issue is indeed that the descriptions are not aligned with the tolerance for ratio.

I am not sure we can easily address this unless when at ratio, we only provide the context response upon release when the hand actually snaps to the tick mark.

@zepumph, let me know what you think of that idea.

It would mean, when using pointer input, if a hand is moved into the fitness area that is considered close enough to ratio, we only provide the object and context responses if they end the drag.

**Comment by zepumph** [comment] 2022-03-21 19:07
@terracoda, I don't remember why we assigned me to this on Friday. Can you note what I should do here?

**Comment by terracoda** [comment] 2022-03-23 17:56
@zepumph, I think you were going to investigate snapping to the Tick Mark when using pointer input.

**Comment by terracoda** [comment] 2022-03-23 18:10
Basically, if we have a tolerance for mouse input to find the ratio, when a learner let's go of the mouse, and they are within the tolerance or fitness, the actual described position of the hand needs to communicate the same thing as the sound and visuals are communicating.

So for example, if the right hand is "on Tick Mark 6" and a leaner moves the Left Hand to be "around Tick Mark 3" and they let go of the mouse, the Left hand should visually snap to Tick Mark 3, and say "on Tick Mark 3", and not "around Tick Mark 3". This is just an example.

I think the sim does snap most of the time, but I have noticed a couple of times when the snapping doesn't seem to work properly. 

Leave it assigned to me until I find a real reproducible example.

**Comment by zepumph** [comment] 2022-03-23 18:47
Over to you sounds great. Thanks for finding a case.

>I think the sim does snap most of the time, but I have noticed a couple of times when the snapping doesn't seem to work properly.

If the issue is that you thought it should snap but doesn't, that is different from the issue where you snap, and the "endDrag" alert still says "around tick mark X." Please let me know if it is either of these, or something else. I remember we couldn't really figure out what the issue was. 

Furthermore, this issue is pretty general, and was (is?) more about the general discussion. Feel free to open another issue if you find one of those specific bugs.

**Comment by terracoda** [comment] 2022-08-05 16:49
Discussed this on August 5th, and I am closing. We cannot address the issue that causes this tension at this time.

**Closed by terracoda** 2022-08-05 16:49 UTC
Labels: dev:voicing, design:voicing
