### ISSUE TITLE
Ratios seem to be a little off with "shuffleListeners" on

### ISSUE THREAD

**Issue by jbphet** [phetsims/ratio-and-proportion#301] opened 2020-12-15 21:41 UTC
This issue was found during code review, see #286.

There is an item in the code review checklist that says, "Does the sim behave correctly when listener order is shuffled?". While testing this, I found that if the suffleListeners query parameter is used, when on the 2nd screen the ratios can be a bit off.  Below is a screenshot, and the feedback is showing that the ratio is correct, but the right hand is positioned at around 20.5 instead of 20.  When the right hand was moved to 20, the feedback no longer indicated the correct ratio (2nd screenshot).

![image](https://user-images.githubusercontent.com/3082831/102275827-37d2eb00-3ee3-11eb-87ef-3473ffeb6133.png)

![image](https://user-images.githubusercontent.com/3082831/102276087-9304dd80-3ee3-11eb-9e8a-f8b74784c5a0.png)

**Comment by zepumph** [comment] 2020-12-29 23:10
I do not think that this has anything to do with ?shuffleListeners. Instead it seems to be because of the narrow range in which you can move the smaller hand (left in this case) and still be in-proportion. I was able to confirm this with and without 
`?shuffleListeners`. To confirm this I recommend using `?log` to print out the exact values of the range.

4/30 is `.13333333333333333`, so use the console logging to try to get as close to that as possible for the left value. When you do that, the right hand is in proportion right on top of 20.

For the next experiment put the right hand on 20.5, and then move the left hand until it is in proportion. Note how visually it looks really quite close to 4, but the value will be more like `.137`.  

I think that this is just a byproduct of how the ratio works. I don't recommend any changes. We purposefully aren't snapping for 0-30 because we think of it as more of a late-stage "super user" exploration strategy, and it has a tendency to snap things out of proportion just as often as snapping into proportion. 

Also note that the narrow range is because of and based on the current target ratio. At range 0-10 we should always get color feedback for the right hand for 2 tick marks in either direction of the target ratio, no matter the target ratio. The left hand will change based on the target ratio though. If target ratio is at 1/2, then we will get color feedback for one tick mark in either direction of in-proportion. In 0-30 terms, the right hand will have color feedback for 6 tick marks in either direction. A target of 1/5 means that the available range to move the left will be just over 1 tick mark to get color feedback. I am finding all of this to be true in the sim with shuffleListeners on.  

Note that when I say "color feedback", it is a proxy for saying that lots of feedback happen, and really I should probably say when ratioFitnessProperty is greater than 0: (0,1]. 

Please review and let me know what you think.

**Comment by jbphet** [comment] 2021-01-27 23:14
> I do not think that this has anything to do with ?shuffleListeners.

Oaky, fair enough.  I messed around with it with and without `shuffleListeners`, and I think you're right.

> I don't recommend any changes.

I'm surprised by this.  I just tried it out on the [recent RC release](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-rc.1/phet/ratio-and-proportion_en_phet.html) and it feels to me like when I have a 1-to-5 challenge with the left hand centered on 4, when the right hand centered on 20 it doesn't seem to me like the right feedback is being given (this is the same scenario as depicted in the pictures above).  This strikes me as incorrect pedagogy.

**Comment by emily-phet** [comment] 2021-01-28 14:33
Hmm, it sounds from my read of this that we aren't able to get the precision needed for the 0-30 tick marks setting that allows for the sim to always show "at ratio" correctly. If that's the case, that is an issue. The sim cannot indicate "at ratio" in the wrong place. 

Perhaps the simplest solution is to remove the 0-30 tick mark option. If the tick marks are too close together for the snapping algorithm that is present otherwise, then perhaps it's just to fine a grid for the sim.

**Comment by zepumph** [comment] 2021-01-28 17:06
>Hmm, it sounds from my read of this that we aren't able to get the precision needed for the 0-30 tick marks setting that allows for the sim to always show "at ratio" correctly

I do not agree fully with this description of the problem. In 0-30 there is no snapping. The issue is that @jbphet feels that it is a problem when the "intent" is to be at 4, but the mouse behavior  moves to something like 4.1. Since it isn't at 4, then the other hand will be off to, in cases where the other hand is larger, we could have larger error show up there. For example 4:20 would turn into 4.1:20.5. Which would look noticeable. This is why in part we added snapping to the 0-10. I personally do not think this is an issue. You can still make a concerted effort to place the hand on 4, and that will effect the other hand to be placed on 20 also.

**Comment by jbphet** [comment] 2021-01-28 21:48
I'm sorry to belabor this, and if @emily-phet says that I should let it go, I will.

The scenario described below was done on https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-rc.1/phet/ratio-and-proportion_en_phet.html

It doesn't seem to me like a lack of "snapping" is at the root of the problem here.  In the screenshot below, I set up a challenge with a 1-to-10 ratio, and then used my pixel ruler app to position the left hand as precisely as I could at a value of 2.  I then moved the right hand to to the top of its allowed range, then slowly moved it down until I got the "success" feedback, and here is where that happened:

![image](https://user-images.githubusercontent.com/3082831/106201090-2bde7800-6175-11eb-9f33-47b1c323d395.png)

That just seems wrong.  The tick mark line for 21 is visible in the "hand hole", the tick mark line for 20 is not.  If I then move the right hand lower, to where it looks perfectly centered on a value of 20 (as shown below), I'm definitely _not_ getting the "success" feedback any longer.  It feels like the "success" zone is above 20, and not centered around it, which is why it doesn't seem related to snapping to me.  It just seems like the success zone is off.

![image](https://user-images.githubusercontent.com/3082831/106201844-4d8c2f00-6176-11eb-9e9e-d5d9b77adc6c.png)

Maybe the problem is that I'm misunderstanding the relationship between the hand positions and their values.  I'm thinking that the center of the hole corresponds to the value.  However, if I am, I believe that at least some of our users will have the same misunderstanding.

**Comment by amanda-phet** [comment] 2021-02-02 02:48
>Maybe the problem is that I'm misunderstanding the relationship between the hand positions and their values. I'm thinking that the center of the hole corresponds to the value. However, if that is incorrect, then I believe that at least some of our users will have the same misunderstanding.

My understanding is that the center of the hole is where the value aligns, so in the screenshot you shared, I see the same thing you do. Looks like a good catch to me.

**Comment by emily-phet** [comment] 2021-02-06 16:10
This is what I originally wrote - after exploring 1:10.
_I played around with the latest sim on phettest - and I agree with @zepumph that this isn't a error, it's an artifact of the current way tolerance is set up. In your example @jbphet, if you move the left hand ever so slightly down (for example, looking at the black outline for the left hands thumb...moving it so that the top of the black line of the thumb is just barely touching the bottom of the black tick mark for Tick Mark 2), I think you'll get the behavior you expect to see for a 1:10 ratio.

The 1:10 ratio in particular produces the biggest challenges for the "amplification" effect of the size we're allowing for the region of space that produces the "at ratio" feedback._ 

Then this last comment got me thinking, and I explored 1:5 and found it actually more confusing! I have to position the left hand in such a specific way (with the black outline of the left hand's thumb just below the target Tick Mark) to avoid getting the kinds of examples that @jbphet is raising.

Now I think we should definitely get rid of "1 to 30". I think the model we're using, coupled with the size of the hands and their outer black outline makes it very difficult to know what value you're actually on for the 1:30 tick marks. While I agree with @zepumph that we do think this will be a far-less-frequently used feature, and most likely for more advanced use of the sim, it is potentially quite confusing. 

@zepumph - I'm assuming it's relatively straightforward (as far as last-minute changes go) to remove the last option of the that combobox...if you think this requires further discussion, just let me know. I can also be available to join the usual Tuesday meeting, if that's helpful.

Alternatives that come to mind (that I don't recommend we pursue at this stage) would be having the tolerance values change when "1 to 30" is selected, and decreasing the size of the black outline on the hands, to help narrow the range of heights that feel like they are "centered" on a Tick Mark.

**Comment by zepumph** [comment] 2021-02-08 22:34
@emily-phet, would you join us for tommorrow's RaP meeting to confirm this change.

Proposal: get rid of the 1-30 tick marks view.

I offer another proposal: Allow snapping to nearest tick mark on 1:20 and 1:30, which we currently aren't. This would remove the minor error in these cases. We could customize the "snap to threshold" to be different from the pretty large value that 1:10 currently has.

Proposal three: (insert wild card here)

I'll send you a calendar invite.

**Comment by zepumph** [comment] 2021-02-09 18:25
From design meeting today, @emily-phet @terracoda @BLFiedler and I decided that snapping would have the desired fix for this situation. We don't though want a complicated workaround that we always have to maintain to support this case. If we find that it is too much work, then we will get rid of 1:30.

@emily-phet also mentioned that with the new preferences menu, this could be the type of thing that we add, as a default-off option, that can be turned on (the 1:30 option, not the snapping).

**Comment by zepumph** [comment] 2021-02-09 20:19
Above we are now snapping 10% of the tick mark above and below for all ranges. The limited paper trail of why we decided no to do this for 1:30 is https://github.com/phetsims/ratio-and-proportion/issues/122#issue-677125113 (not much to go on there). I think this behavior is nicer than it was, and the snap is very subtle. @emily-phet will you please review. Anything else for this issue?

**Comment by zepumph** [comment] 2021-02-13 04:56
I'm going to proceed with this into the next RC, but we can keep tweaking (most likely there will be at least one more RC spot check after rc.2.

**Comment by emily-phet** [comment] 2021-02-19 00:06
The snapping feels nice for all tick mark options. 

One thing I do notice is that for the 1:30 case, the "snap-to" range is smaller than the "at ratio" range. So you can get the sim "at ratio" near a tick mark, and wiggle it around quite a bit without it snapping onto a single gridline. This is probably also true for 1:20, but seems hardly noticeable. 

I think leaving it as is is probably just fine. This is far improved, and I think will avoid much of the confusion we were trying to address across tick mark options. If we were going to try to address what I noticed in 1:30, it might be something like, narrow the "at ratio" range to also be something like the 10% you're using for the snapping behavior. I'm not sure of the challenge of that or the downstream repercussions, so unless @zepumph you really want to try it, I'm fine with leaving this as is.

**Comment by zepumph** [comment] 2021-02-22 22:23
I think that will prove really challenging. I am thinking about this in two ways.

1. The case you outline above is not general, because it assumes that when you are "in proportion", that the desired value is the same as the value of the tick mark. Though likely this is what the user is trying to do, it is quite possible that it is not, so I wouldn't want to assume this, 
2. The "in proportion threshold" and the "snap to tick mark threshold" are in two different units. Snapping is determined based on the position of the hand, where as the in-proportion threshold is based on fitness units. I don't think it is an oversimplification to just say outright that it is very challenging to equate these two values, and to just leave it at that. Let me know if you want more details as to why.


From these sentiments, I am ready to close this issue. Please reopen if there is anything more you would like to discuss.

**Closed by zepumph** 2021-02-22 22:23 UTC
Labels: status:ready-for-review
