### ISSUE TITLE
CT distance should have changed when this function is called

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#277] opened 2020-12-09 16:48 UTC
```
ratio-and-proportion : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1607529602430%22%2C%22timestamp%22%3A1607532099746%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: distance should have changed when this function is called
Error: Assertion failed: distance should have changed when this function is called
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/assert/js/assert.js:25:13)
at HandPositionsDescriber.getDistanceProgressString (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:298:15)
at HandPositionsDescriber.getSingleHandDistance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:229:42)
at RatioHalf.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/RatioHalf.js:382:45)
at RatioHandNode.a11yCreateContextResponseAlert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/RatioHalf.js:179:52)
at RatioHandNode.alertContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/sun/js/accessibility/AccessibleValueHandler.js:404:44)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/RatioHalf.js:289:28)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/scenery/js/listeners/DragListener.js:338:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/scenery/js/listeners/PressListener.js:628:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/9/2020, 9:00:02 AM

----------------------------------

ratio-and-proportion : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1607529602430%22%2C%22timestamp%22%3A1607531418183%7D&brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: distance should have changed when this function is called
Error: Assertion failed: distance should have changed when this function is called
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/assert/js/assert.js:25:13)
at HandPositionsDescriber.getDistanceProgressString (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:298:15)
at HandPositionsDescriber.getSingleHandDistance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:229:42)
at RatioHalf.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/RatioHalf.js:382:45)
at RatioHandNode.a11yCreateContextResponseAlert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/RatioHalf.js:179:52)
at RatioHandNode.alertContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/sun/js/accessibility/AccessibleValueHandler.js:404:44)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/RatioHalf.js:289:28)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/scenery/js/listeners/DragListener.js:338:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/scenery/js/listeners/PressListener.js:628:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/9/2020, 9:00:02 AM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1607529602430%22%2C%22timestamp%22%3A1607531317774%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: distance should have changed when this function is called
Error: Assertion failed: distance should have changed when this function is called
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/assert/js/assert.js:25:13)
at HandPositionsDescriber.getDistanceProgressString (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:298:15)
at HandPositionsDescriber.getSingleHandDistance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:229:42)
at RatioHalf.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/RatioHalf.js:382:45)
at RatioHandNode.a11yCreateContextResponseAlert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/ratio-and-proportion/js/common/view/RatioHalf.js:179:52)
at RatioHandNode.alertContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/sun/js/accessibility/AccessibleValueHandler.js:404:44)
at RatioHandNode.onInteractionEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/sun/js/accessibility/AccessibleValueHandler.js:714:14)
at RatioHandNode.handleBlur (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/sun/js/accessibility/AccessibleValueHandler.js:696:16)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/scenery/js/input/Input.js:1822:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607529602430/scenery/js/input/Input.js:1854:12)
id: Bayes Chrome
Snapshot from 12/9/2020, 9:00:02 AM
```

**Comment by zepumph** [comment] 2020-12-10 17:39
This was caused by last minute changes in #262, I wanted to make an assumption about when we try to get distanceProgress, but I think instead we need to be flexible, even if distance hasn't changed.

**Comment by zepumph** [comment] 2020-12-10 17:40
This should be fixed, I'll check back on CT later today.

**Closed** 2020-12-23 21:34 UTC
Labels: priority:2-high, status:ready-for-review, type:automated-testing
