### ISSUE TITLE
"Lock Ratio" unlocks itself with shuffleListeners on

### ISSUE THREAD

**Issue by jbphet** [phetsims/ratio-and-proportion#300] opened 2020-12-15 21:29 UTC
This issue was found during code review, see #286.

There is an item in the code review checklist that says, "Does the sim behave correctly when listener order is shuffled?".  While testing this, I found that if the `suffleListeners` query parameter is used, when on the 2nd screen if the "Lock Ratio" checkbox is set, the box unchecks itself and the hands stop moving together if the hand on the right is moved.

**Comment by zepumph** [comment] 2020-12-30 01:54
From my best estimates, this is happening because of the relationship between two central listeners in the model.

In RAPRatio, the tupleProperty is created, and then immediately linked to with reentrant charaticteristics to make sure that if the tuple is locked, changing one of them will correctly update the other.

Outside of the RAPRatio, the model's unclampedFitnessProperty looks at the two values of the tuple to calculate the fitness of the ratio as it pertains to the target.

There is a fundamental order dependency here. If the fitness is calculated before the tuple has taken its correct and final values, then the fitness will yield incorrect results. In this particular case, this bug occurs when the difference is enough to cause the model to snap out of proportion for an instance before RAPRatio's listener can bring the other value along (the "locked" feature support). When the model goes out of proportion, even for one instant, it causes the ratio to unlock:

https://github.com/phetsims/ratio-and-proportion/blob/38e8a17979c5cd39649a4291bb7d6926303ef24c/js/create/view/CreateScreenView.js#L79-L87


This is yet another place where there is a listener order dependency that I don't know how to get around, and also don't really know what the priority is. For now I will mark this on hold until we decide a better philosophy over in https://github.com/phetsims/scenery/issues/1131

**Comment by zepumph** [comment] 2021-02-12 01:13
Commits over in https://github.com/phetsims/scenery/issues/1131 have fixed this issue. I am not able to reproduce this with shuffle listeners on now. I'm going to close this, please reopen if desired.

**Closed by zepumph** 2021-02-12 01:14 UTC
Labels: status:on-hold
