### ISSUE TITLE
Long strings make sims unusable

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#305] opened 2020-12-15 23:17 UTC
For https://github.com/phetsims/QA/issues/582. Images taken on iPadOS 14 Safari.
When strings are longer than the English strings, this pushes the hand columns to the side. On iPad, these can go off the screen an cause other odd overlaps with stringTest=long.
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/102283933-9488d280-3ef0-11eb-843e-e37df2e2b663.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/102283936-95216900-3ef0-11eb-9f9c-f8c7550b1b6e.png)

**Comment by zepumph** [comment] 2020-12-15 23:23
Yeah thanks, duplicate of #273.

**Closed by zepumph** 2020-12-15 23:23 UTC
Labels: type:i18n

**Comment by zepumph** [comment] 2020-12-15 23:39
No worries! There are approximately 100 million issues open right now.
