### ISSUE TITLE
Potential clipping of "singing" sound while using the lock ratio button

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/ratio-and-proportion#229] opened 2020-11-06 00:06 UTC
We observed this weird clipping sound during the interview. We are not sure if its a bug or a product of the recording. Could you investigate @jbphet we also noticed the "singing" sound to be inconsistent. Here is a clip of the issue. [Clipping](https://drive.google.com/file/d/17fRrsiDsV9kK3dQgolwSEEbwskXBB6QG/view?usp=sharing)

**Comment by terracoda** [comment] 2020-11-06 14:44
@jbphet, could you please have a look when you are next working on sound for RaP?

The interview seemed to think the "clicking" was because of the looping sound, and @emily-phet says that is likely not the reason.

**Comment by jbphet** [comment] 2020-11-06 18:34
@Matthew-Moore240 and @terracoda - To help me in duplicating this behavior, please let me which platforms (OS, OS version, and hardware manufacturer) you were using when you saw and heard the problems.

**Comment by terracoda** [comment] 2020-11-09 13:25
@jbphet, for me it happens when I am using VoiceOver & Safarii on macOS 10.13.6, and for the interview the participant was also using VoicOver & Safari, but on macOS 10.14.

**Comment by terracoda** [comment] 2020-11-09 13:40
@jbphet, apologies, this "clicking" does not happen on my system, though in the zoom clip, some clicking is clearly heard.
The issue that happens on my system is #230.

**Comment by zepumph** [comment] 2020-11-10 20:05
I cannot get this to reproduce on firefox or chrome with windows. It sounded really bad on the recording though, and perhaps would be easy to realize when a platform was having that trouble.

**Comment by terracoda** [comment] 2020-11-10 23:11
Well, as long as it is not because of the record loop, maybe we can wait and see in QA?

**Comment by terracoda** [comment] 2020-11-10 23:12
I'll test it on my partner's macAir!

**Comment by zepumph** [comment] 2020-11-24 21:00
@jessegreenberg and I were able to get bad clipping on staccato, in proportion, and singing/moving in-proportion while using safari. It was also badly clipping for all common code ui sounds like reset all, home screen buttons, and radio buttons. I put this here because it likely is general to all sounds.

This was only on safari/mac. safari 13.1.2

**Comment by jbphet** [comment] 2020-11-24 22:15
Assigning to @Ashton-Morris to test on his Mac, since it's fairly new and I was wondering if this problem could be with the hardware/software implementation on older Macs.

**Comment by emily-phet** [comment] 2020-11-30 19:57
@jbphet - @Ashton-Morris is out now until January. 

I just tried this on my computer (2019, macOS Catalina, 10.15.7) and the choir sound is quite static-y with lock ratio. I've never heard it sound like this before (though I often use the sim with sound off, since I tend to do it early in the morning when family is asleep). 

I was just using the latest on phettest.

**Comment by jbphet** [comment] 2020-12-01 20:01
I am not able to duplicate any clipping on the Macbook Air that I have available to me, which is running OSX 10.12.6 and Safari version 12.1.2.  I tried it with VoiceOver on and off, and didn't hear clipping in either case.  I also tried it in Chrome on that same device and heard no clipping, again regardless of whether VoiceOver was on or off.  @emily-phet and I are meeting today, perhaps she can demonstrate the problem that she is seeing over Zoom.

Also, I tried running version 1.0.0-dev.71, since @zepumph mentioned that it didn't have the clipping problem in his test environment, but that version wouldn't run for me at all - it hits the `this.ariaValueText.replaceAll is not a function` error that has been reported elsewhere, such as in https://github.com/phetsims/projectile-motion/issues/237.

I have a number of ideas about things to try, but can't really do much unless I'm able to duplicate the problem.  @KatieWoe - can you please see if you can duplicate this on any of the devices that you have and then, if you can spare one, I'll come get it and will use it to test and debug the problem if possible.

**Comment by jbphet** [comment] 2020-12-01 21:28
By the way, I do notice a bit of a pause in the sound when the direction of motion is changed while moving the hands with "Lock Ratio" on.

**Comment by KatieWoe** [comment] 2020-12-01 21:30
I haven't been able to reproduce this device on Jordan (which is the device I would be most able to spare). I tried with and without audio ducking, on both master and latest dev. I'm still willing to lend you the device if you think it will help. It is Mac 10.14.7.

**Comment by KatieWoe** [comment] 2020-12-01 21:56
Quick correction. I was on Mac 10.14.6. Safari is 14.0.1

**Comment by jbphet** [comment] 2020-12-01 23:50
@emily-phet and I just duplicated the really bad sound experience described in https://github.com/phetsims/ratio-and-proportion/issues/229#issuecomment-733230605 above.  It happened during a Zoom meeting where @emily-phet was sharing her screen and sound and ran the sim in Safari.  The sound for everything was horribly distorted.  However, when she loaded the sim into Chrome and Firefox, the sound was fine.  She switched back and forth between the browsers several times during the session, and disconnected from and reconnected to Zoom, and the problem stayed consistent, i.e. the sound was terrible in Safari and fine in the other browsers.  However, when she was not connected to Zoom, the sound was fine, even the "singing" sound.

To follow up, I just duplicated with @KatieWoe over Zoom, and she was using Jordan, the Mac she describes above.  Same problem, so we're definitely on to something.

While working with @KatieWoe, we tried two other simulations with sound - Faraday's Law and Gravity Force Lab - and the sound was fine on those sims, so it may be something that is specific to Ratio and Proportion.

**Comment by jbphet** [comment] 2020-12-01 23:52
@Matthew-Moore240 - When you observed the clipping, were you sharing screens?  Can you duplicate the issue when *not* sharing screens?

@zepumph - When you experienced the bad sound described in https://github.com/phetsims/ratio-and-proportion/issues/229#issuecomment-733230605, were you sharing screens?

**Comment by emily-phet** [comment] 2020-12-02 00:00
Just noting that I found Ratio and Proportion open in another browser window (probably the same one I noticed the poor sound issue in yesterday). It again has poor sound in safari - while not having Zoom on.  I [recorded it](https://drive.google.com/file/d/1v3rHkiJVFyE-CCuEYCbB3y7yRbP4K6hU/view?usp=sharing) (for posterity!). 

I'm not sure if it's helpful, but I tried to gather all info I could think of about the scenario. Here's the info from the "Report problem" in the sim:
Name: Ratio and Proportion
URL: https://bayes.colorado.edu/dev/phettest/ratio-and-proportion/ratio-and-proportion_en.html?brand=phet&ea&debugger
Version: 1.0.0-dev.73 (unbuilt)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
Language: en-us
Window: 1215x708
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

And here's the info about my computer:
<img width="278" alt="Screen Shot 2020-12-01 at 3 56 45 PM" src="https://user-images.githubusercontent.com/5109055/100810882-3dfa9f00-33ee-11eb-9476-745e957e3418.png">

**Comment by emily-phet** [comment] 2020-12-02 00:01
@jbphet - regarding your [question](https://github.com/phetsims/ratio-and-proportion/issues/229#issuecomment-736894970) for @Matthew-Moore240 - the original observation of this issue was during a remote interview when screens were being shared on zoom.

**Comment by zepumph** [comment] 2020-12-02 05:27
>@zepumph - When you experienced the bad sound described in #229 (comment), were you sharing screens?


Hmm, I don't really remember, @jessegreenberg and I were pairing, but his mac is his second computer, and sometimes he just tests things on his own, and sometimes we add the mac to the zoom call and he shares his screen with it. I can do more investigation with him next Tuesday during our meeting if you would like. Just assign me back if you would like that or any other help.

**Comment by jessegreenberg** [comment] 2020-12-02 15:21
I am pretty certain we were sharing screens with zoom on my Mac. In fact, I just confirmed by using two devices here that if I run the sim from master without sharing screens I don't get any clipping. But if I do share screens while sharing audio the clipping happens. If I share screens without sharing audio there is no clipping, so sharing audio is required. This is using macOS 10.15.6 Safari 13.1.2.

**Comment by zepumph** [comment] 2021-01-04 22:11
So I guess the next question here is is it is worth investigating audio clipping that occurs when sharing screen with zoom. @emily-phet should this block publication? Adding label until we decide it doesn't since we are soon getting to RaP RC time.

**Comment by BLFiedler** [comment] 2021-01-12 18:10
I think it is reasonable to not let this block publication. It is fairly context specific, not reproduced by QA, and seems as though it can be fixed with a page refresh.

**Comment by zepumph** [comment] 2021-01-12 19:09
I think this would be a good issue to get to at some point, since it seems to be sim-specific (see https://github.com/phetsims/ratio-and-proportion/issues/229#issuecomment-736894362). We also live in a remote world, and will want to be able to use zoom for interviews and pairing in the future. I'll remove the blocking label, but I'm going to keep this open.

**Comment by zepumph** [comment] 2021-01-19 19:35
Over to @jbphet for further investigation.

**Comment by zepumph** [comment] 2021-01-19 19:36
Feel free to create a tambo issue and close this one if that is easier/better for you.

**Comment by jbphet** [comment] 2021-02-01 23:05
> Feel free to create a tambo issue and close this one if that is easier/better for you.

So far, ratio-and-proportion is the only sim the exhibits the problem, so I'm not ready to create a general issue for this just yet.

**Comment by jbphet** [comment] 2021-02-01 23:20
I just tried to duplicate this by setting up a Zoom call between a MacBook Air and my main development machine, opening R&P in Safari from master, and sharing screens+sound on the dev call.  At first, sound didn't work at all, meaning that it wasn't playing on the Mac nor was it coming over the Zoom link.  I stopped screen sharing, and then several sounds (such as the Reset All sound) played.  I started screen sharing again, and sound still wouldn't work.  I opened Chrome on the Mac, loaded the sim, and sound worked fine on the Mac and came through on the Zoom call just fine.  I returned to Safari and loaded Faraday's Law in an effort to determine whether the problem was specific to R&P.  Sound worked fine for Faraday's Law in Safari, and also sounded fine over the Zoom link.  I then loaded up R&P again in Safari, and at that point the sound worked fine, and it sounded fine across Zoom.  I tested the "in-proportion" sound, and there was no problem with it over the Zoom link.

It's hard to draw any general conclusions from this, but here are a few observations:
- There is clearly something a little weird going on with the interaction between shared sound over Zoom when using Safari.  So far, we've seen certain sounds being distorted, and sound not being produced at all, but the problem is intermittent and we don't yet know how to reproduce it consistently.  We don't yet know if this problem is unique to Ratio and Proportion, but it's the only sim so far where I've encountered problems.
- The distorted audio with the choir sound over Zoom doesn't happen every time.  During this particular round of testing, I wasn't able to make it happen at all.
- So far, this doesn't seem like a "low hanging fruit" sort of issue to me, given that it's hard to duplicate.  One option might be assign it to the QA team to see if they can come up with a good way to replicate the problem and, if they can, spend some development time on it after that.
- It's *possible*, though unlikely, that the problem was fixed in a Safari update.

**Comment by jbphet** [comment] 2021-02-01 23:38
In the testing described in my previous comment, audio started working after loading a different PhET sim with sound (in this case Faraday's Law) and then reloading Ratio and Proportion.  If we have QA work on this, it would be good to figure out if this works every time, and if it fixes the clipping problem too.  If so, we could potentially use this as a workaround until we figure out how to fully solve the issue.

**Comment by zepumph** [comment] 2021-02-01 23:56
Good idea, and thanks for taking a lead on this. I'd prefer to get an update from @emily-phet at this point if she would like us to pass this on to QA for reproducing, or if we should marks as a wontfix, close, and note it for future interviews. The main determining factor is the burden it would have on interviews (thus I feel like it is not my call).

**Comment by emily-phet** [comment] 2021-02-07 15:11
@terracoda Do you have strong feelings about continuing to work on a solution for this?

From my reading of the above comments, and my (poor) memory, it seems this problem has only been observed in RaP, was first observed in early November, and found intermittently since then...and is perhaps getting harder to reproduce (or at least, we're having less success reproducing it when folks have tried). 

Since Zoom seems to be consistently updating itself now with various fixes, I wonder if this problem will likely solve itself over time (if not already). If @terracoda is ok with it, let's mark this as "wontfix" and just wait and see if it pops up again.

**Comment by terracoda** [comment] 2021-02-16 17:59
I do not have strong feelings about this issue. My interviewee was convinced it was a looping issue, but in comment https://github.com/phetsims/ratio-and-proportion/issues/229#issuecomment-725023252 my understanding was that it was definitely not a looping issue.

I have only experience this issue when sharing screens over zoom, and I agree as Zoom improves, it sharing capabilities should improve for video and sound.

I am comfortable with "won't fix".

**Comment by terracoda** [comment] 2021-02-16 18:11
I will go ahead and close this issue.

**Closed by terracoda** 2021-02-16 18:11 UTC
Labels: type:wontfix
