### ISSUE TITLE
[VoiceOver] "Range" is spoken twice when it has focus

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#532] opened 2022-11-18 21:25 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.0.1

**Browser**
safari 16.1 

**Problem description**
With VoiceOver, when I tab to the range combobox, "range" is said twice. It also happens when closing the combobox.

**Steps to reproduce**
1. Turn on VoiceOver
2. Tab to and select (numbered) tick marks
3. Tab to Range Combobox--you should here "range" repeated
4. Change the range to something else and press return--it will be repeated here too

**Visuals**

https://user-images.githubusercontent.com/87318828/202805015-fb25f0bf-31b6-44aa-9cea-49aa93d0afc8.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.1/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.1 2022-11-11 22:40:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1544x712
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment] 2022-11-28 14:22
@zepumph I see this issue on master. Perhaps it is specific to VoiceOver + safari? You said you were on a Windows machine.

**Comment by zepumph** [comment] 2022-11-30 16:06
I'll try to reproduce on my iOS+ safari, and then solicit help if I need a mac. @emily-phet and I agree that so long as we understand what is happening, and it seems minor, if we can't fix it is ok to proceed.

**Comment by zepumph** [comment] 2022-12-02 00:33
@marlitas and I went to town on this issue, and found that when the ComboBoxButton labelTagName is a `p`, the there is no issue with duplication. I felt like it was a pretty slight change for that fact that it fixed this bug, but it definitely is a workaround since safari+VO is the only spot where this is an issue.

@jessegreenberg do you think this is acceptable? I'm happy to discuss if you have concerns, but please assign back to me.

**Comment by zepumph** [comment] 2022-12-05 22:44
Done and ready for confirmation in next version.

**Comment by jessegreenberg** [comment] 2022-12-07 19:00
I can't think why this would be an issue. I also don't know why it was previously a span. Seems good to move forward with and hopefully this change will will work for all screen readers.

**Comment by Nancy-Salpepi** [comment] 2022-12-07 20:54
Things sound good in 1.2.0-rc.2 with VoiceOver + safari on the mac, but a little weird on the iPad. 'Range' is said once in a swipe (with a different voice). Then you have to swipe again. It again says 'Range' in a different voice before stating the range. 


https://user-images.githubusercontent.com/87318828/206292471-7d67625d-25d3-4c90-b34d-1c466b3a5aad.mov


Here is what it sounds like on the mac:

https://user-images.githubusercontent.com/87318828/206293282-712b6d2c-dea5-4592-8a79-8203176736ab.mov

**Comment by zepumph** [comment] 2022-12-07 21:45
After discussing with @jessegreenberg, we are totally fine with this behavior. Thanks! Closing

**Closed by zepumph** 2022-12-07 21:45 UTC
Labels: type:bug, status:ready-to-cherry-pick, dev:description

**Comment by KatieWoe** [comment] 2022-12-07 22:29
Noting that I'm seeing this with Jaws + Chrome as well.
