### ISSUE TITLE
Screen shifts when hand is moved at bottom of screen with Chromebook

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#534] opened 2022-11-21 19:52 UTC
**Test device**
Chromebook

**Operating System**

**Browser**
chrome

**Problem description**
https://github.com/phetsims/qa/issues/852

When I drag a hand to to the bottom of the screen using the mouse or keyboard, the screen shifts a little. It was hard to video (because I was also moving), but look at the Challenge combobox to see the movement. 

This doesn't happen on my mac, but I did notice that with interactive highlights on, the highlight size changes when I move the hand at the bottom of the screen (video 2). 

**Steps to reproduce**
1. On either screen, grab a hand and drag in all the way to the bottom and back up again. 

**Visuals**

https://user-images.githubusercontent.com/87318828/203146052-48b51985-7e93-49ee-a302-26f840b12aba.mov

https://user-images.githubusercontent.com/87318828/203146084-c2c9e315-f2e3-4723-9eba-142f063ba59b.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.1/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.1 2022-11-11 22:40:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1544x712
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment] 2022-11-25 20:35
I remember working on this in an ISLC sim for a time, and I got no where with it. These small layout inconsistencies can be tough to track down. I looked into the Helper to see if there was anything obvious about the layout that could be trouble, with not luck. I also couldn't reproduce this on my windows/Chrome.

As for the second. This is alright, and is also in the published version. I honestly think it looks better that it only expands way over the nav bar if it has to. 

I am going to close this issue, but thanks for the two bugs.

**Closed by zepumph** 2022-11-25 20:35 UTC
Labels: type:bug
