### ISSUE TITLE
Camera Input doesn't work with LoL

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#531] opened 2022-11-18 19:26 UTC
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/852
When running the sim in Legends of Learning, if you enable the camera input a warning pops up saying no camera is available.
**Steps to reproduce**
1. Enter the sim in the LoL harness with the `cameraInput=hands` parameter.

**Visuals**
![lolhands](https://user-images.githubusercontent.com/41024075/202785303-fc5bcf08-7c3d-48c5-bcfc-4d980a08ee71.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.1/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.1 2022-11-11 22:40:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by emily-phet** [comment] 2022-11-21 16:03
I don't think we need to support the camera input / lol combo.

**Comment by BLFiedler** [comment] 2022-11-21 16:35
Is this generally true for the sim in any iframe or unique to LoL?

**Comment by KatieWoe** [comment] 2022-11-21 16:42
The hands worked in the iframe, but not in LoL

**Comment by zepumph** [comment] 2022-11-22 00:51
I'm happy to not support this, but I'd like to know what's going on. That message is most often because you have another tab opened that is using you webcam. What's a link that I can reproduce this? Feel free to message me instead if you don't want that on github.

**Comment by zepumph** [comment] 2022-11-24 01:58
Also, I noticed the URL is in the "Troubleshooting details", but without the query string. Do you purposefully remove those, or is there a bug somewhere? It may be nice to include those in the issue unless there is a reason not to. Let me know if you want to talk to try to reproduce.

**Comment by KatieWoe** [comment] 2022-11-28 15:43
I didn't purposely remove it. I'm not sure why it isn't there.

**Comment by zepumph** [comment] 2022-11-30 15:59
@emily-phet and I don't think we should look into this any further. Closing

**Closed by zepumph** 2022-11-30 15:59 UTC
Labels: type:bug
