### ISSUE TITLE
Voicing reads combo box in a previously used locale

### ISSUE THREAD

**Issue by stemilymill** [phetsims/ratio-and-proportion#528] opened 2022-11-17 03:39 UTC
For https://github.com/phetsims/qa/issues/852

**Test device**
Dell laptop

**Operating System**
Win10 21H2

**Browser**
Chrome 107.0.5304.107

**Problem description**
With voicing enabled, I was switching between different locales and using keynav. When I had switched from Danish to English, and shift+tabbed back to play with the hands, voicing read over "Challenge 3" (which was currently  selected in the combo box) as "Opgave 3" with 3 as english three and Opgave in an English pronunciation.

When I entered the combo box, voicing read everything as expected, including "Challenge 3."

**Steps to reproduce**
I am still working on this. After recording the video below I changed the locale to German and then back to English and the self-voicing behaved as normally expected.

**Visuals**

https://user-images.githubusercontent.com/85511101/202348427-7459cdf5-3b5e-48a6-849b-2bd3421c409a.mp4

<details><summary>Troubleshooting information:</summary>
<p>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.1/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.1 2022-11-11 22:40:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1493x775
Pixel Ratio: 1.125/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</p>
</details>

**Comment by zepumph** [comment] 2022-11-17 18:43
Voicing is an "english only" feature, so this bug is actually that voicing doesn't turn off when switching locale. I'll take a look.

**Comment by Nancy-Salpepi** [comment] 2022-11-17 22:51
@zepumph voicing seems to be working correctly with mac + safari/chrome.  With Voicing enabled, when I switch locale it becomes disabled and I hear "Voicing off. Only available in English."

**Comment by Nancy-Salpepi** [comment] 2022-11-21 14:01
Also not seeing this issue with the Chromebook.

**Comment by stemilymill** [comment] 2022-11-21 16:40
when the locale was danish, voicing was actually correctly disabled, but when I switched back to english and voicing was re-enabled everything except the combo box was being read correctly

**Comment by Nancy-Salpepi** [comment] 2022-11-21 17:17
Thanks for the clarification @stemilymill! 
I was able to reproduce with the mac and with Chromebook using these steps @zepumph:

Steps:
1. Enable Voicing 
2. In the Localization tab, change the locale to Dansk or any other language --Voicing becomes disabled
3. Exit the dialog
4. On the Discover Screen, change the Challenge--ex. Pick Challenge 2
5. Change the locale back to English --Voicing becomes enabled
6. Exit dialog and tab to the Combobox --The current challenge will be read in Dansk. 
7. Open the combo box--Voicing is in English.

**Comment by zepumph** [comment] 2022-11-23 23:21
Wonderful. You are seriously talented folks. Thanks! I also found the same issue with voicing name response for the combo box list items.

To cherry pick: https://github.com/phetsims/sun/commit/ddb02404eee474d6998f752ba57078345238c1cf

**Comment by zepumph** [comment] 2022-12-05 22:44
Done and ready for confirmation in next version.

**Comment by KatieWoe** [comment] 2022-12-07 21:27
This looks good in rc.2

**Comment by Nancy-Salpepi** [comment] 2022-12-09 13:55
This seems to still be broken in rc.2 with the keyboard dialog this time. 

Steps:
1. Turn on Voicing
2. Switch to another locale--ex Italian (voicing turns off)
3. Open the keyboard dialog
4. Switch back to English (voicing turns back on)
5. Open the keyboard dialog and tab through--it will be a combination of English words and the English voice pronouncing the Italian words. 

https://user-images.githubusercontent.com/87318828/206717868-c102a42a-d773-4fee-8f58-da6ef16dc2e5.mov

**Comment by zepumph** [comment] 2022-12-16 19:48
Excellent! I can reproduce in rc.2 but not on master. I believe it to be because of https://github.com/phetsims/scenery-phet/commit/005be16a04936795e842c1255d074b4c40c9c3e6 which I thought wouldn't matter for RAP, oops. I can cherry pick that into the rc, but first will you confirm that it is not reproducible on master please?

**Comment by Nancy-Salpepi** [comment] 2022-12-16 22:28
I can't reproduce on master either. yay.

**Comment by zepumph** [comment] 2022-12-16 22:30
Wonderful!

**Comment by zepumph** [comment] 2022-12-16 22:30
I'll cherry pick https://github.com/phetsims/scenery-phet/commit/005be16a04936795e842c1255d074b4c40c9c3e6 but I will also make sure that fixes it and doesn't need any other changes from that monster issue.

**Comment by zepumph** [comment] 2023-01-03 01:14
I also had to cherry pick https://github.com/phetsims/axon/commit/2e738ee36181ea147d06c462556e9ffe42667fe9 also. But now it is all cherry picked. Cherry picked. QA, feel free to close if all is well.

**Comment by Nancy-Salpepi** [comment] 2023-01-04 13:07
Looks good in 1.2.0-rc.3! Closing

**Closed by Nancy-Salpepi** 2023-01-04 13:07 UTC
Labels: type:bug, type:i18n, status:ready-to-cherry-pick, dev:voicing
