### ISSUE TITLE
Both hands "0" behavior when ratio is locked?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#289] opened 2020-12-14 19:43 UTC
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/582.
When the ratio is 1:1 or equivalent, pressing 0 to jump both hands to 0 can cause temporary or even permanent freezing of the sim. When this is done, the hands do not jump to 0. Using the arrow keys only sometimes works, and other numbers must be pressed to unstick the hands. Sometimes this takes a few tries. If you click with the mouse while the bug is occurring, the freeze becomes permanent and the page must be refreshed.
**Steps to reproduce**
1. Go to the second screen and set the ration to 1:1
2. Make the hands match the ratio
3. Lock the hands in the ratio
4. Use the both hands keyboard setting
5. Use arrow keys to move hands as low as allowed (not always needed, but seems more consistent)
6. Press 0
7. Press 0 again until hands actually jump to zero
8. Repeat testing other keyboard inputs during bug.
9. While bug is occurring, use mouse to try and drag hand out of frozen position

**Visuals**
![consoleerrors](https://user-images.githubusercontent.com/41024075/102127518-d723af80-3e09-11eb-8616-67e4fe68802a.gif)
![fullfreeze](https://user-images.githubusercontent.com/41024075/102127530-dbe86380-3e09-11eb-88ab-dffa1f794af8.gif)
<img width="958" alt="maximumcallsizeratio" src="https://user-images.githubusercontent.com/41024075/102127563-e1de4480-3e09-11eb-8d1a-0e6643493a5b.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.77/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-dev.77 2020-12-08 00:32:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment] 2020-12-14 19:55
Also noting that there seem to be other oddities with the 0 button, even if they don't cause this bug (such as pressing it once to get one speed/volume of notes, and pressing it again to see a slight color shift and new speed/volume of notes).

**Comment by brooklynlash** [comment] 2020-12-15 17:05
Other behaviors I noticed from this bug: 
1. When clicking zero for the first time, the sound is like when the hands are not in ratio, when they actually are. Once you click out of keyboard navigation, the sound stops completely and the background color is not in ratio when it actually is. 
2. At the frozen spot, you can't do anything with the sim, but putting keyboard nav back on and clicking the numbers again makes it work like normal and then move to the correct zero point, BUT still again act as if they are not in ratio, I am not sure if this was intended in the design because 0:0 is technically not a 1:1 ratio right? @amanda-phet was this intended?
3. When clicking zero for the second time, the hands go to the actual zero point and then are movable.

**Comment by zepumph** [comment] 2020-12-16 16:06
There is a current design in which a locked ratio cannot go past a hard coded threshold. It is currently .5, but will soon be .1 (see https://github.com/phetsims/ratio-and-proportion/issues/257). So I think we just need to respect the locked ratio, and disallow this input listener from trying to access 0 in it is not in the enabled range.

**Comment by zepumph** [comment] 2020-12-16 17:06
With https://github.com/phetsims/ratio-and-proportion/issues/309 done, I think that we can just pass in the enabledRangeProperty to BothHandsInteractionListener, and do one of two things. We can constrain to the enabledRange, or we can ignore input requests that are outside of that range. I think that doing the former will be best for now.

**Comment by zepumph** [comment] 2020-12-22 19:53
Now you will no longer get this bug. `0` input from both hands with snap to the contrained range, so when that is locked, it is just over .1 of a default tick mark. @BLFiedler I think this is in need of a design review, this is based on what we discussed in the previous design meeting last week. Is it acceptable that pressing `0` doesn't go to `0` because the ratio is locked, and so `0` is out of the enabled range?

It may be helpful to test with `?log` to see actual model values.

**Comment by BLFiedler** [comment] 2020-12-22 20:30
Hm. I may be a bit confused. If I have the ratio locked on screen 2, pressing 0 breaks Lock Ratio (as does pressing any other number) and puts both hands at a value of 0 (verified in log).

**Comment by zepumph** [comment] 2020-12-22 22:24
Pressing 0 is supposed to break the lock, but for me it does not go to zero, it goes to the min range of the lock ratio at the time of 0, which is .01.

![image](https://user-images.githubusercontent.com/6856943/102938326-9276c480-4458-11eb-855c-015ea2774ec9.png)


Is that different from what you get. Is that even desirable? The code is like this because we want to support the ability to stay in lock ratio range when the target is 1:1 and you press 0 (which currently doesn't break lock, but puts both values a bit above .01 because that is the min of the locked ratio range.

**Comment by BLFiedler** [comment] 2020-12-23 22:08
Updated, sorry. Didn't realize the connection between regular ol phettest connection and bayes. I see the same behvaior.

this does run us into the issue of "what is 0:0" if they are expecting it to go to that value. Personally, I believe even for the 1:1 case, going to 0 breaks the lock ratio because 0:0 =/= 1:1.

However, if you're using the 1:1 with a mouse, you can't accomplish the same behavior, and I think that is more important here given our other choices in this region.

So, let's leave it as it is I think.

**Comment by zepumph** [comment] 2021-01-05 20:45
We decided that when locked and target is 1, pressing "0" in the both hands interaction should not work. In addition to this patch. @terracoda will come up with an alert to say in this case.


```diff
Index: js/common/view/BothHandsInteractionListener.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/BothHandsInteractionListener.js b/js/common/view/BothHandsInteractionListener.js
--- a/js/common/view/BothHandsInteractionListener.js	(revision e79314ec684b3f02471c8c9897aa64231935397f)
+++ b/js/common/view/BothHandsInteractionListener.js	(date 1609879274448)
@@ -182,6 +182,10 @@
 
             const wasLocked = this.ratioLockedProperty.value;
 
+            if ( wasLocked && this.targetRatioProperty.value === 1 && i === 0 ) {
+              return;
+            }
+
             // unlock the ratio because we are snapping out of locked ratio, if target is 1, then we are maintaining
             // that ratio with this input and we can keep the ratio locked.
             if ( wasLocked && this.targetRatioProperty.value !== 1 ) {

```

**Comment by terracoda** [comment] 2021-01-07 15:29
I was assuming I should put the newly needed context response in this issue, but I just discovered a problem with closed #227, so I think it is best to keep all Lock Ratio responses in that issue.

I hope that's okay.

**Comment by zepumph** [comment] 2021-01-07 18:57
That sounds good to me. I will unassign you to this, and assume that you will take care of whatever context responses needed over in https://github.com/phetsims/ratio-and-proportion/issues/227

**Comment by zepumph** [comment] 2021-01-07 19:33
The patch from https://github.com/phetsims/ratio-and-proportion/issues/289#issuecomment-754888778 was applied above. Closing

**Closed by zepumph** 2021-01-07 19:33 UTC
Labels: status:blocks-sim-publication, type:bug
