### ISSUE TITLE
Exiting Full Screen while moving hand prevents release of hand when mouse is no longer pressed

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#523] opened 2022-11-15 19:59 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.0.1

**Browser**
safari 16

**Problem description**
For https://github.com/phetsims/qa/issues/852, when I press the 'esc' key to exit Full Screen while moving a hand with the mouse, releasing the mouse doesn't release the hand. I need to click on the screen to release it. 

This is also seen in published.
I couldn't reproduce this with mac + chrome.

**Steps to reproduce**
1. On either screen, select Full Screen from the PhET Menu
2. Move one of the hands using your mouse while you press 'esc'
3. Stop clicking the  mouse/trackpad, but move the mouse around the screen.

**Visuals**

https://user-images.githubusercontent.com/87318828/202013818-b51bd9cf-9710-4892-b77f-dac29f3e7194.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.1/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.1 2022-11-11 22:40:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1544x712
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment] 2022-11-22 00:38
@chrisklus and I were not able to see any differences in input events between safari and chrome on macos, though we confirmed chrome works. We also reproduced this with dragging in number play. I am going to move this to scenery as a browser bug.

**Comment by zepumph** [comment] 2022-11-24 02:04
I created https://github.com/phetsims/scenery/issues/1505, for now I do not consider this blocking, as it is a mouse/keyboard interaction only when exiting fullscreen mode on safari. Since there is a common code issue now, I'm going to go ahead and close this. @emily-phet please reopen and mark this as blocking if you disagree. Thanks!

**Closed by zepumph** 2022-11-24 02:04 UTC
Labels: type:bug
