### ISSUE TITLE
CT reentry detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#263] opened 2020-12-02 16:26 UTC
```
ratio-and-proportion : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606869370143/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1606869370143%22%2C%22timestamp%22%3A1606883363721%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=false, oldValue=true
Error: Assertion failed: reentry detected, value=false, oldValue=true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606869370143/assert/js/assert.js:25:13)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606869370143/axon/js/Property.js:277:15)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606869370143/axon/js/Property.js:178:14)
at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606869370143/axon/js/Property.js:350:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606869370143/ratio-and-proportion/js/create/view/CreateScreenView.js:182:42
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606869370143/axon/js/TinyEmitter.js:71:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606869370143/axon/js/Property.js:280:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606869370143/axon/js/Property.js:178:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606869370143/axon/js/DerivedProperty.js:91:13)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606869370143/axon/js/TinyEmitter.js:71:18)
id: Bayes Chrome
Snapshot from 12/1/2020, 5:36:10 PM
```

**Comment by zepumph** [comment] 2020-12-02 17:29
Yes thanks, this will be covered by #258.

**Comment by zepumph** [comment] 2020-12-07 22:41
I can't reproduce this after, https://github.com/phetsims/ratio-and-proportion/commit/6d1ece40ec63539d8998784a8c738ce3e7fcbc91 closing

**Comment by zepumph** [comment] 2020-12-08 20:30
I encountered this again this morning, even though I don't see it on CT. This patch fixed it, but I'm unsure this is the right way.

```
    this.lockedProperty = new BooleanProperty( false, {
        reentrant: true
      }
    )
```

**Comment by zepumph** [comment] 2020-12-12 00:13
I still haven't seen this on CT again.

**Comment by zepumph** [comment] 2020-12-18 20:34
I haven't hit this again recently, and it fails loudly enough that I feel good since a dev test in under RaP's belt. Closing

**Closed by zepumph** 2020-12-18 20:34 UTC
Labels: type:automated-testing, type:bug
