### ISSUE TITLE
Error message appears with camera input: hands + voicing 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#501] opened 2022-09-02 16:57 UTC
**Test device**
macbook air m1 chip

**Operating System**
macOS 12.5.1

**Browser**
Safari 15.6.1

**Problem description**
For https://github.com/phetsims/qa/issues/831, the sim freezes when using camera input: hands and voicing. 
I was able to get it to occur 3 times. I didn't feel like I was doing anything in particular....just moving my hands up and down, stopping every once in a while, making the freeze gesture etc. It didn't occur until after playing with the sim for a few minutes. 

**Visuals**
<img width="500" alt="Screen Shot 2022-09-02 at 12 12 16 PM" src="https://user-images.githubusercontent.com/87318828/188201077-40a68e66-8e12-4fbc-8896-f797ebb4268b.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.31/phet/ratio-and-proportion_all_phet.html?cameraInput=hands
Version: 1.2.0-dev.31 2022-08-24 16:50:40 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Language: en-US
Window: 1322x704
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment] 2022-09-02 17:46
I was also able to reproduce this with mac + chrome (although I still don't know exactly what triggers it). 

I was incorrect though--the sim isn't frozen. The error message keeps increasing in number so the performance is affected. The voicing still works and buttons make noise, but any changes I make don't appear on the screen.

https://user-images.githubusercontent.com/87318828/188209034-25b3b55d-e0c0-40cf-a827-ccc2208c4a7e.mov

**Comment by Nancy-Salpepi** [comment] 2022-09-08 15:47
With Win10 + FF, I left the sim open for 30 minutes with the camera input: hands and voicing activated. When I returned, there was a message that FF crashed. 
![firefox crashed](https://user-images.githubusercontent.com/87318828/189166984-374af21a-7283-4319-bc7f-1777f6f91f32.JPG)

**Comment by zepumph** [comment] 2022-09-08 17:23
I played around for about 10 minutes and couldn't reproduce, that said. The error message is really helpful, and I'm pretty sure that I can make this graceful, because from the best of my understanding, this is from the library, and not from our code.


RE: https://github.com/phetsims/ratio-and-proportion/issues/501#issuecomment-1235761633, it is expected that an error like this would completely crash the sim, that some functions were still working can be ignored.

RE: https://github.com/phetsims/ratio-and-proportion/issues/501#issuecomment-1240899536, see  separate issue 
https://github.com/phetsims/ratio-and-proportion/issues/510

**Comment by Nancy-Salpepi** [comment] 2022-09-09 18:54
@zepumph I wasn't able to reproduce with Win10 + chrome and @KatieWoe mentioned that she wasn't able to either with Win11 + chrome. Perhaps this is a mac thing?

**Comment by zepumph** [comment] 2022-10-19 15:59
I believe that this bug should be fixed by the above commit. Ready for testing in next QA test.

**Comment by zepumph** [comment] 2022-11-03 21:28
Actually @Nancy-Salpepi, could you try to reproduce this now? Either with master or with https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.35/phet/ratio-and-proportion_all_phet.html?cameraInput=hands

**Comment by zepumph** [comment] 2022-11-07 19:24
No worries! Very helpful. Can you please test on master, with assertions enabled. I added some logging that may help if you have a chance to copy the data structure that is printed if you ever see a note like, "broken hand landmark input:"

**Comment by Nancy-Salpepi** [comment] 2022-11-07 22:58
not sure if this a different error, but this popped up in the console "21 hand positions expected"

<img width="978" alt="Screenshot 2022-11-07 at 5 57 01 PM" src="https://user-images.githubusercontent.com/87318828/200433297-078d7a3e-ef23-4661-91a9-bb865108e911.png">

**Comment by zepumph** [comment] 2022-11-08 15:12
That last line where it says "Assertion failed" is exactly right! Thank you. Though I am surprised that it didn't show a larger red "error" with a stack of calls below it (like you see on CT). Anywho. . .  Very helpful and I think I can clean this up, but I'm still so unsure how it detects a "hand" without any position data. Can you describe how you are reproducing this error; I have never encountered this problem on Windows 11 Chrome.

**Comment by Nancy-Salpepi** [comment] 2022-11-09 14:08
@zepumph after clearing my history I am no longer able to reproduce this issue.
I will definitely still keep a look out for this in future testing.

**Comment by Nancy-Salpepi** [comment] 2022-11-16 22:25
@zepumph I was not able to reproduce this problem in 1.2.0-rc.1

**Closed** 2022-11-16 22:36 UTC
Labels: type:bug, status:ready-for-review, dev:alt-input, dev:voicing
