### ISSUE TITLE
Both hands at zero always counts as almost there

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#288] opened 2020-12-14 18:54 UTC
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/582
No matter what the ratio is set to, (any of the challenges on the first screen or any combination on the second) if both hands are at 0 it is counted as being almost at the ratio but not quite. The screen will be a darker green, but not the darkest green. And the loud click will play as a sound effect, rather than the "you got it" sound. This is particularly odd if the ratio is set at 1:1.

**Visuals**
<img width="857" alt="allthealmost" src="https://user-images.githubusercontent.com/41024075/102122428-b1df7300-3e02-11eb-8d03-46aa7c224d00.png">
<img width="813" alt="morealmost" src="https://user-images.githubusercontent.com/41024075/102122431-b1df7300-3e02-11eb-9246-f78e44c40a2a.png">
<img width="879" alt="almostthere" src="https://user-images.githubusercontent.com/41024075/102122433-b2780980-3e02-11eb-8b9a-f6a4c64f434a.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.77/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-dev.77 2020-12-08 00:32:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by terracoda** [comment] 2020-12-14 20:52
Agreed, it seems a bit odd, but the hands can't be in proportion if one value is set to zero.
That said, I am a little confused about the extreme difference in left and right values, e.g. 1:10, and the sim is still communicating "extremely close". 

<img width="997" alt="Screen Shot 2020-12-14 at 5 13 45 PM" src="https://user-images.githubusercontent.com/1902116/102133716-19f87e00-3e30-11eb-8bfa-7771b63463d3.png">

Maybe in terms of mathematical possibilities, it is "extremely close"? For example, I think if you could get the left hand to 0.01 and the right hand to 0.10, the hands would be in proportion. But there is a minimum exploration point for the left hand.
<img width="997" alt="Screen Shot 2020-12-14 at 5 15 28 PM" src="https://user-images.githubusercontent.com/1902116/102133750-2b418a80-3e30-11eb-81bf-f801f5569df7.png">

There is a discussion about the minimum value over in https://github.com/phetsims/ratio-and-proportion/issues/275#issuecomment-741811163.

**Comment by KatieWoe** [comment] 2020-12-14 21:08
I'm not sure what it should be mathematically. My instinct was that, at 0, they would match no matter the values. If the ration is 1:10, and the left hand is at 0, 0*10 = 0 so the right hand should be at 0 too. Not sure if my instinct is right though. Would @amanda-phet know?

**Comment by zepumph** [comment] 2020-12-15 00:10
The current behavior is based on a relatively extensive design process where we decided that the fitness (metric for how close the ratio is to tartet) is determined in part based on physical distance from what the target Ratio would look like, and not just by comparing the current Ratio value to the target. This is why a current Ratio of 0, or even x/0 can yield description and color output that are closer to the target than you might expect if you were just comparing the ratio value solely. I think @emily-phet should join this conversation for comment.

**Comment by amanda-phet** [comment] 2020-12-15 01:57
Just jumping in here since I was mentioned... If they are actually at 0, as @terracoda 's screenshots seem to communicate, then I would consider a constraint to not allow 0 in this sim, especially if 0 isn't allowed in the ratio number pickers. If it's desirable to include 0 as a possibility in the play area, then the feedback should be the farthest from green if one or both hands is on 0. If they are *close* to 0, everything is fine and I'm sure the sim is responding appropriately. But allowing 0 is extremely problematic, especially if there is green feedback.

**Comment by emily-phet** [comment] 2020-12-15 14:43
@amanda-phet Agreed, you shouldn't ever get "at ratio" green/sound/responses when one or both hands are at zero. This constraint is in place. 
Keeping zero in the sim was strongly emphasized as being important by our math ed collaborator, who has done significant research with related proportion learning tools. 

I'm more concerned about the behavior I observe related to @KatieWoe 's comments here - where you can move a hand from the zero position upward, and get feedback that first that you're approaching "at ratio", and then that you're moving away from "at ratio" without ever getting "at ratio". When we were setting the threshold values, I thought we had checked together that the thresholds were placed such that this did not occur anywhere. 

Here's a short video of this occurring, with instructions below to reproduce: https://drive.google.com/file/d/1iHP-ENBzI037s7Ew1LiZE26fEACTaaJq/view?usp=sharing

To do this - set My Ratio to 1:10, place the left hand at zero, then move the left hand up just high enough to snap to a position just above zero. Then move the left hand up a tiny bit higher than that. Next, place the right hand at zero, then move the right hand upward. Visually, you see the screen start out light green (when the right hand is at zero), then the screen turns darker green, then lighter green again as you continue moving the right hand upward. It never reaches at ratio green.

@zepumph Is there a way for us to visualize the fitness/"at ratio" mappings so that we can identify and address the threshold issues quantitatively? Can we plot, for each challenge ratio, the ratio vs fitness mapping, so that we can identify the problem areas graphically and adjust the threshold taking into account all mappings at once?

**Comment by emily-phet** [comment] 2020-12-15 14:44
Assigning @BLFiedler as well, for his thoughts on graphing this problem, and potential solutions.

**Comment by amanda-phet** [comment] 2020-12-15 15:50
@terracoda 's first screenshot in https://github.com/phetsims/ratio-and-proportion/issues/288#issuecomment-744703728 indicates that both hands are at 0. So there is a bug related to that scenario- maybe there are two issues going on in this thread?

**Comment by emily-phet** [comment] 2020-12-15 16:26
@amanda-phet Yes, they are at zero. They are also indicated as "close to challenge ratio" not "at challenge ratio". This is intended, not a bug. You can be "close to ratio" when at 0, 0. You just can't be "at ratio".

**Comment by KatieWoe** [comment] 2020-12-15 16:31
@emily-phet in that case, there is a secondary oddity I saw. If you press 0 to jump to zero while the hands are already there, the shade of green and audio feedback may change slightly, which still seems odd.

**Comment by zepumph** [comment] 2020-12-15 19:11
From design meeting today, we see that there are two ways of thinking about the "fitness" of a ratio. It is clear that @KatieWoe and @amanda-phet are likely thinking of this from a conceptual way, in which a hand on 0 could be infinity (or N/A) away from the target ratio.

@emily-phet and others in the design team in designing fitness thus far has taken that into consideration as a component of fitness, but we have also used physical distance into consideration. When either hand is at 0, you may only need to move the hands a small amount to achieve the target ratio in-proportion.

@terracoda, @BLFiedler @zepumph and @Matthew-Moore240 discussed a solution today.
* Removing the "hollywood" zone, and treating a case of either hand on 0 as an edge case in which we make the fitness a large negative value. The screen will be white, and the description would be "extremely far from ratio". This would try to remedy the conceptual difference between a ratio of 0:X, 0:0 or X:0 to other ratios. 
  *In addition, we may want to a description to the 0 case to have ratio be "undefined" instead of "extremely far from" from. 

We still feel like there is a good change that we will keep the definition of fitness as a function of physical distance. Especially since we are so close to publication, but we want to discuss further, likely with @emily-phet.

**Comment by zepumph** [comment] 2020-12-15 19:15
@amanda-phet, with your math background, can you please comment, on the tradeoffs or weirdness of including physical distance in our fitness algorithm as it pertains to the edge case of either hand as 0.

**Comment by terracoda** [comment] 2020-12-16 22:10
In @emily-phet's video, it looks to me like the left hand is at 0.01 (1 shift key step) above zero.
When the right had is moved to 0.02 (2 shift key steps) above zero, there is no ding for ratio and then the screen goes light again if the right hand is moved higher.

However, if the left hand is at 0.02 (2 shift key steps) above zero, and the right hand is moved to to 0.04 (4 shift key steps) above zero, the sim will ding and screen will go dark green.

I think removing the hollywood zone (as we discussed in yesterday's design meeting) will solve the issue shown in @emily-phet's video (0.01 and 0.02 will be a possible ratio).

I think the big question is whether or not we want physical distance (closeness to a possible ratio if hands were just above zero in this case) to help determine proximity to ratio (sonification and screen color) when one or both hands are zero, and mathematically ratio is "undefined". 

It is true that the hands are physically close the challenge ratio, but do we want the sim to be communicating that when one or both values are at zero.

**Comment by zepumph** [comment] 2021-01-05 21:17
Today @terracoda, @BLFiedler, @emily-phet and I discussed this further. There was one camp that was very interested in having a denominator at 0 cause a white screen, and there was another camp that wanted to keep it as is on master. The latter camp's justification was that the fitness is based on hand position proximity, and not on comparing the current ratio. 

We decided to go with master as is, where 0/0 is a shade of green ("extremely close to challenge ratio"). Though we feel like more mathematically focused people may not agree, this compromise feels like it is not incorrect (based on position), while also not calling attention to a region of the sim that we don't want to draw attention to, and we don't want an edge case behavior to cause more questions from learners that the sim isn't set up to answer. Closing

**Closed by zepumph** 2021-01-05 21:17 UTC
Labels: status:blocks-sim-publication, type:bug
