### ISSUE TITLE
H1 is wrong place on Home Screen

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#357] opened 2021-02-21 17:34 UTC
<img width="820" alt="image" src="https://user-images.githubusercontent.com/1902116/108633157-51e1fa00-744d-11eb-87bb-4acf6befaeef.png">

Just noticed this strange ordering and duplicate content. Not sure when this got introduced.

The Home Screen starts off with the correct content, but the sim name is not in an H1 element, then later after the intro the sim name appears again and this time in an H1 element.

Fix by moving H1 to top of page and removing duplicate content of the sim name.

**Comment by terracoda** [comment] 2021-02-21 17:36
I should mention RC 2 https://github.com/phetsims/QA/issues/609, I am not sure RC 2 has started.

**Comment by zepumph** [comment] 2021-02-22 21:19
This is caused by https://github.com/phetsims/ratio-and-proportion/issues/321

**Comment by zepumph** [comment] 2021-02-22 21:33
@jessegreenberg, can you please review since this is common code. Note that this is just a minor bug from commits in https://github.com/phetsims/ratio-and-proportion/issues/321 where we created `ScreenView.pdomTitleNode`.

**Comment by jessegreenberg** [comment] 2021-02-25 17:32
I see, thanks for fixing. Change looks reasonable to me and PDOM content for the home screen looks good in the a11y view.

**Comment by zepumph** [comment] 2021-02-25 23:47
Excellent! Thanks.

**Comment by Matthew-Moore240** [comment] 2021-03-05 22:53
This looks to be fixed. Closing.

**Closed by Matthew-Moore240** 2021-03-05 22:53 UTC
Labels: dev:a11y, status:ready-for-qa, type:a11y-bug
