### ISSUE TITLE
Sound does not work on iPad in Safari

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#37] opened 2020-05-01 20:45 UTC
After experimenting with dev.15 on an iPad, it does require Chrome for the audio to work (as a note for future interviews). Safari does not work.

_Originally posted by @BLFiedler in https://github.com/phetsims/ratio-and-proportion/issues/31#issuecomment-622473585_

**Comment by BLFiedler** [comment] 2020-05-01 20:46
@jbphet , @emily-phet said you might be able to look into this or direct @zepumph on how to address it? Something within tambo or WebAudio?

**Comment by emily-phet** [comment] 2020-05-03 14:45
@jbphet 
Can you look into this this week? We're doing interviews with sound in the near future and it would be ideal to not have to ask those using a touch device to download Chrome.

**Comment by emily-phet** [comment] 2020-05-03 14:47
@zepumph Not sure if this is something sim-specific or something that will need to be addressed in Tambo...but thought @jbphet might be able to get to the root of the issue quickly.

**Comment by jbphet** [comment] 2020-05-04 15:44
I'll look into it.  I have a reasonably new PhET iPad available so I should be able to do at least some level of debugging from here.

**Comment by jbphet** [comment] 2020-05-04 20:50
Hmmm.  Sound for the [dev.5 version](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.15/phet/ratio-and-proportion_en_phet.html) works fine for me in mobile Safari on the PhET device named "Pauling", which is an iPad Air 2 (A1566) running iOS 13.4.  Master also works fine on this device.

@BLFiedler - can you record in this issue the device(s) where you saw the problem, including iOS version?

@KatieWoe - can you see if you can duplicate the problem on any of the devices at your disposal?

I won't be able to track this down unless I can duplicate it.  If we find that it only occurs on some devices, we can work out a way to get me one of those.

**Comment by BLFiedler** [comment] 2020-05-04 21:02
I tried it some more on my end. 

During my initial testing, I didn't seem to be able to get anything other than the pick-up sound.

Now, the sound proportion sound itself does cut off **sometimes**, **rarely** when I go into the options menu or reset the sim. I'm not sure the exact cause because it appears a bit inconsistent. I've tried changing window focus, resetting sim, refreshing page.

I feel like I'm going a bit crazy because I was definitely not getting sound the first time I opened the sim on the iPad in Safari.

If no one else is having this problem, maybe it is localized. Sorry for the non-existent goose chase.

This is on 6th gen iPad, iOS 13.3.1.

**Comment by KatieWoe** [comment] 2020-05-04 21:04
Did you go to another tab/app/leave the sim? Sometimes that interrupts sound for safari, and it is a known issue.

**Comment by BLFiedler** [comment] 2020-05-04 21:07
Ah- okay. Got it. When I open the link from another tab, terrible noises or no noise happen. Changing tabs itself is not the problem. However, the interviewees will be opening from another tab or page most likely, so that is not desired. Can anyone else confirm that happens? Try opening the dev version from your e-mail or this issue on the iPad so that a new tab opens?

**Comment by KatieWoe** [comment] 2020-05-04 21:10
I'm getting the terrible noises whenever I refresh or open the tab. Leaving and coming back to safari seems to fix it?

**Comment by BLFiedler** [comment] 2020-05-05 15:27
https://drive.google.com/open?id=1ufQ4MfzbcTOlNE0CiqwfJRxoBqMRpZcV

Caught the sound on video. Had just opened the sim from an e-mail to try out resizing. Note this is dev.16. Refreshing fixed it.

**Comment by zepumph** [comment] 2020-05-05 19:33
Could not reproduce on 7th gen 13.2.3, or after software update to 13.4.1. This was on dev.15.

**Comment by KatieWoe** [comment] 2020-05-05 19:49
I had a misunderstanding of the issue. Discussed over zoom with @jbphet just now. I thought the normal warble sound was a bug. Since it is intended, I was unable to reproduce this I believe. I think that, when I left safari briefly and came back, the intended warble sound was gone and only pick up and drop noises happened. Device is 6th gen iPad on iPadOS 13.4.1.

**Comment by BLFiedler** [comment] 2020-05-05 20:04
So, difficult to reproduce and perhaps tied to bigger issues around focus & tab navigation (and opening/closing).

Unless it is obvious how to proceed to any of the developers, it may be best to put this on hold and it is possible I will need to consider with respect to the interview protocol how to handle this (it may include asking them to refresh before interacting with the simulation).

**Comment by BLFiedler** [comment] 2020-05-05 20:31
@jbphet If it isn't obvious what to do here, please close this issue and I'll open another (more specific) issue if it becomes a problem for interviewing.

**Comment by jbphet** [comment] 2020-05-05 21:19
@BLFiedler - mostly sounds good, but I would suggest you update the iPad in question to 13.4, since @KatieWoe, @zepumph, and I were all unable to reproduce the problem on that iOS version (from the notes above, it looks like @zepumph skipped 13.3, which is the version on which you're seeing the problem).  If you could do that and then test and see if the issue is gone, I'd feel better about closing this.  At least we'd know then whether it seems more tied to an iOS version or a specific hardware device.

**Comment by Ashton-Morris** [comment] 2020-05-05 21:25
I tried to replicate the bug on chrome and safari on iPad and did not hear the noise.

**Comment by BLFiedler** [comment] 2020-05-06 15:53
Still happens on 13.4.1. Maybe it's specific to this iPad. The sound dropping out that Katie experienced I have also experienced, but that is hard to reproduce on my side and I am more reliably getting the weird quality to the sounds in the video I showed above when I open the sim from an external link.

**Comment by jbphet** [comment] 2020-05-08 16:21
@BLFiedler - I guess I'll go ahead and close this issue since there isn't much I can do.  If it continues to be a problem for you, please reopen or open a new one, and we'll work out a way that I can get the iPad where the issue is occurring and do some testing and debugging on it.

**Comment by BLFiedler** [comment] 2020-05-08 16:24
If I can make it to campus at some point I'll try to grab the other ipads that were purchased alongside this one and see if it's reproducible across them. I'll keep the ball in my court for now. Thanks, John!

**Comment by zepumph** [comment] 2020-09-02 02:36
From investigation into https://github.com/phetsims/ratio-and-proportion/issues/80, it seems like these may be the same issue. Reopening and closing that one.

**Comment by zepumph** [comment] 2020-09-28 22:18
Noting that the "not working" sound in this issue has been described as "static-y" over in https://github.com/phetsims/ratio-and-proportion/issues/80. I cannot reproduce this on my iPad, I tried loading the sim from slack, and from phetmarks in the "unbuilt" mode hosted from a local server on my Windows machine.

**Comment by zepumph** [comment] 2020-09-28 22:22
Oops, I wasn't trying to close this issue. Instead, I was hoping that we could get QA to try to reproduce this bug. Perhaps spending 1 hour or less of time. On this version.

https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.65/phet/ratio-and-proportion_en_phet.html

@KatieWoe can you please assign someone to take on this job? The issue of broken sound has only been reported on Safari.

Thanks!

**Comment by KatieWoe** [comment] 2020-09-29 15:48
Tried to reproduce on iPadOS 14 Safari, with no luck. Do you want any other platforms looked at @zepumph?

**Comment by zepumph** [comment] 2020-09-29 19:16
Thanks for taking a stab @KatieWoe, it has only been reported on iPad, so no other platforms needed. 

@BLFiedler, @emily-phet et all discussed this today at design meeting today, and no one has encountered this for a while. That coupled with QA's difficulty in reproducing makes us feel good about closing this, and reopening if it ever becomes a problem.

**Closed by zepumph** 2020-09-29 19:16 UTC
Labels: dev:sonification, type:bug
