### ISSUE TITLE
Both hands interaction sonification inconsistent during interview

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/ratio-and-proportion#230] opened 2020-11-06 00:12 UTC
We also noticed that during the Both Hands interaction that a lot of the sounds were very inconsistent. Could you investigate @jbphet again we are not sure if its a bug or a weird recording hiccup. Here is another clip of the issue. [Inconsistent sound](https://drive.google.com/file/d/1p0l0pyMxJoTm3S4rd7zwsTSMQWtEuWFN/view?usp=sharing)

**Comment by terracoda** [comment] 2020-11-06 14:46
@jbphet, this "interruption" of the sounds also happens for me, so I am not sure if it might be a VO-specific issue. The interviewee was using VO and I also use VO.

**Comment by jbphet** [comment] 2020-11-06 18:33
@Matthew-Moore240 and @terracoda - To help me in duplicating this behavior, please let me which platforms (OS, OS version, and hardware manufacturer) you were using when you saw and heard the problems.

**Comment by terracoda** [comment] 2020-11-09 13:32
I also posted the system info in issue #229VoiceOver & Safarii on macOS 10.13.6, on a 2015 macBook Pro, and for the interview the participant they were also using VoicOver & Safari, but on macOS 10.14 and on a macAir. I don't know how new.

**Comment by zepumph** [comment] 2020-11-10 19:59
I don't think this is a sound bug. This is in the way the staccato sounds were implemented. They only play when Property says that the both hands is being interacted with. I feel like me logic for that doesn't correctly account for how focus/interaction may change when the screen reader is on. I'll take a closer look.

**Comment by emily-phet** [comment] 2020-11-17 14:36
Unassigning @jbphet for now.

**Comment by zepumph** [comment] 2020-11-24 02:27
This is what I want to test on a mac, but I don't have one to test. Perhaps I can pair with @jessegreenberg on this to see what is happening here. On windows with or without NVDA, I always have had great success with the sound starting on first both-hands key press, and not stopping until tab navigating away.

**Comment by zepumph** [comment] 2020-11-24 21:05
@jessegreenberg and I discovered that we could reproduce this bug in safari in  https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.71/phet/, but not on master. I'm not sure what has changed, and if it is a tambo thing or a RaP thing.

**Comment by zepumph** [comment] 2020-11-26 02:44
I looked around commits in RaP, scenery, and tambo, and nothing stood out as the cause of this fix. It would be nice to know, but I don't know how else to investigate without taking up more time of someone with a mac.  

@Matthew-Moore240 can you please confirm that this is fixed for you on master/mac/safari and feel free to close.

**Comment by terracoda** [comment] 2020-11-30 17:45
@zepumph, considering your comment in https://github.com/phetsims/ratio-and-proportion/issues/230#issuecomment-733232729, shall we leave this issue for QA? 

I use a mac all the time and I have not experienced this issue.

**Comment by zepumph** [comment] 2020-11-30 20:58
Sounds good. I'll just leave open for QA. Great idea!

**Comment by zepumph** [comment] 2020-12-05 01:51
QA, when you get here, please take a look at the behavior in the video in the original comment, and then try to reproduce with the "Both hands interaction" (when the keyboard focus highlight is around both hands). I could only see the bug in safari.

**Comment by KatieWoe** [comment] 2020-12-11 22:18
I did note that the sound stops when keyboard nav focus leaves. Even when you come back to it. Is this alright @zepumph?
https://drive.google.com/file/d/151Zc6cyhgar9JyNq_w6DInmNuuDEARYf/view?usp=sharing

**Comment by zepumph** [comment] 2020-12-12 03:55
Yes, it should not begin again until you focus AND interact with it (move it) again.

**Comment by KatieWoe** [comment] 2020-12-17 22:37
I don't think we saw this. We will keep an eye out during future tests.

**Comment by zepumph** [comment] 2020-12-18 00:58
I think enough time has been spent on it! Closing. Thanks for all your help.

**Closed by zepumph** 2020-12-18 00:58 UTC
Labels: dev:sonification, status:ready-for-qa, type:bug
