### ISSUE TITLE
Voicing statement incorrect when tabbing to Reset All button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#529] opened 2022-11-18 01:40 UTC
**Test device**
MacBook Air (m1 chip0

**Operating System**
13.0.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/852, when I tab to the Reset All button, Voicing says "Sim screen restated. Everything reset." instead of "Reset All."

**Steps to reproduce**
1. Turn on Voicing
2. On either Screen, tab to Reset All button

**Visuals**

https://user-images.githubusercontent.com/87318828/202596871-fa09bb88-ad61-4fb3-b031-5dfe5f784f52.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.1/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.1 2022-11-11 22:40:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1544x712
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment] 2022-11-23 21:57
Duplicate of https://github.com/phetsims/ratio-and-proportion/issues/524 (though it didn't seem like it), fixed by https://github.com/phetsims/ratio-and-proportion/issues/524#issuecomment-1322576755). Cherry pick will happen over there. Closing

**Closed by zepumph** 2022-11-23 21:57 UTC
Labels: type:bug, dev:voicing
