### ISSUE TITLE
Lines around screen icons persist

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/ratio-and-proportion#352] opened 2021-02-15 23:44 UTC
### Test Device

iPad Pro

### Operating System

iPadOS 14.4

### Browser

14.0.3

### Problem Description

For https://github.com/phetsims/QA/issues/609. The lines that appear around the screen icons when you hover over them or click them persist. See gif.

### Gif

![issue](https://user-images.githubusercontent.com/60749003/108002416-cbd93580-6fac-11eb-9388-c629864243dc.gif)

**Comment by zepumph** [comment] 2021-02-16 01:53
I don't have time to test right now, but I wonder if this is something to do with our recent changes involving PressListener.looksOverProperty

**Comment by zepumph** [comment] 2021-02-16 17:40
I tried reproducing in the RC on my iPad and can't. I press on a screen and then press and drag my finger across the buttons but the highlight works as expected for me. You are on an iPad, but use language that suggests that you may have a mouse plugged in for this test.

Can you please provide some more detailing on how to reproduce?

**Comment by liam-mulhall** [comment] 2021-02-16 18:28
@zepumph, I forgot to mention that I was using a stylus. I just checked and I wasn't able to reproduce by tapping with my fingers. Up until now, I haven't seen a stylus-specific bug, so I'll be more cognizant of this in the future.

**Comment by liam-mulhall** [comment] 2021-02-16 18:34
I added https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#note-on-tablets. I will message @KatieWoe about this as well.

**Comment by zepumph** [comment] 2021-02-17 00:21
See https://github.com/phetsims/scenery/issues/1156 for the common code issue tracking this. In short, this is because there is logic in scenery that is hard coded to only fire if it is a `Touch` pointer, but we actually want to fire it on `Touch` OR `Pen`.

**Comment by zepumph** [comment] 2021-02-22 22:13
I think this will be fixed with cherry-picks explained in https://github.com/phetsims/scenery/issues/1156#issuecomment-783712440.

I'll mark this as ready for testing.

**Comment by liam-mulhall** [comment] 2021-03-10 04:57
My Apple Pencil is broken. I've ordered a new part for it, but it'll be two days before it gets here. I don't think this should block progress on the spot check since it's such an edge case, @zepumph and @KatieWoe.

**Comment by liam-mulhall** [comment] 2021-03-15 21:26
Fixed in https://github.com/phetsims/QA/issues/617.

**Closed** 2021-03-15 21:27 UTC
Labels: status:ready-for-qa, type:bug
