### ISSUE TITLE
Double tap on spinner sometimes adds/takes away 3 rather than 2

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#340] opened 2021-02-03 22:53 UTC
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/601
When using the track pad, doing a double tap on the My Challenge spinners would normally increment by two. However, it seems to increment by three instead.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬:‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-rc.1/phet/ratio-and-proportion_all_phet.html?stringTest=double
Version: 1.0.0-rc.1 2021-01-26 23:41:16 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
Language: en-US
Window: 1280x687
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment] 2021-02-04 18:46
Seen on ChromeOS as well. It also happens when doing things like opening/closing the My Challenge box.

**Comment by terracoda** [comment] 2021-02-08 17:08
I wonder if this is because a long press can activate continuous increments or decrements?

I can't seem to reproduce the triple value change with 2 clicks on the track pad.

**Comment by KatieWoe** [comment] 2021-02-08 17:11
It's also probably not going to be a typical interaction. I mostly saw when I was rapid clicking through the spinner, and being off by one and going back and adjusting it doesn't seem to problematic.

**Comment by zepumph** [comment] 2021-02-09 00:47
I tried to reproduce this for ~10 minutes on chrome and firefox, and couldn't. given the challenge to reproduce, and the ease to fix the mistake, I think we should close this. If anyone disagrees please reopen and I'll try to take a closer look.

**Closed by zepumph** 2021-02-09 00:47 UTC
Labels: type:bug, type:wontfix
