### ISSUE TITLE
Lines in grid selection radio buttons have inconsistent widths

### ISSUE THREAD

**Issue by jbphet** [phetsims/ratio-and-proportion#171] opened 2020-09-02 19:03 UTC
On my external monitor screen, which is a Dell LCD (I can figure out the model number if anyone needs it), the lines in the radio buttons that are used to select the grid mode have inconsistent widths, regardless of how the sim window is sized or scaled.  Specifically, the center line is thinner than the upper or lower lines.  Here is a screenshot that shows the problem.

![image](https://user-images.githubusercontent.com/3082831/92024789-e039b680-ed1b-11ea-9a91-5ad668bdc5ff.png)

In the grand scheme of things, this is a fairly minor UI issue, so I wouldn't recommend spending a ton of time on it, but it's worth a look to see if there is some scaling that is being done that could be modified to make this go away.

**Comment by zepumph** [comment] 2020-09-02 19:28
Over to @emily-phet to prioritize.

**Comment by zepumph** [comment] 2020-09-02 19:29
I was able to reproduce it sometimes, and then not others. For example once on startup it was there, then I zoomed into the component and it wasn't, and then when I zoomed out again it wasn't present from what I could tell.

**Comment by emily-phet** [comment] 2020-09-04 17:21
@zepumph - @amanda-phet made this artwork as other sims have done. I wonder if this is something others have encountered. Could you bring this up in a dev meeting or something, just to get a sense if others have encountered it? 
In general, this is not a high priority. Regarding if it needs to be addressed prior to publication, I actually don't know. I don't know if this is something that would typically be required to be fixed per usual PhET standards for visual display. This would be something to ask of other devs, etc. as well. It doesn't seem like a big deal to me, but we usually don't design the visual display in our a11y work.

**Comment by amanda-phet** [comment] 2020-09-04 20:28
I'm trying to figure out why the icons aren't as crisp as the 'eye' icon, but I don't know where to find the eye icon to verify the resolution of it. Maybe the resolution of these gridline icons could be higher. They are currently larger than what is needed, but they sometimes seem a little fuzzy to me. Anyway, I haven't been able to reproduce this issue. @jbphet what browser are you using? I think Firefox is known to cause this issue more than other browsers. 

Usually we see these kinds of scaling artifacts with thin lines because it can be a matter of a pixel lining up just right, but I'm not entirely sure how we've fixed it in the past.

**Comment by amanda-phet** [comment] 2020-09-04 20:40
The most fool-proof solution is to make the icons in code.

**Comment by zepumph** [comment] 2020-09-08 16:19
> @jbphet what browser are you using?

I think it may also be helpful to know what resolution your screen/monitor goes to.

> but I don't know where to find the eye icon to verify the resolution of it

That one is font awesome, and the math to draw it can be seen [here](https://github.com/phetsims/sun/blob/b01905a3c21ef3a12396f2c45f29280798c8c49e/js/FontAwesomeNode.js#L46). Likely because it is SVG instead of PNG.

@amanda-phet do you want to give me copy of these images with a very high resolution, and we can see if that fixes @jbphet's problem.

>The most fool-proof solution is to make the icons in code.

Yes I agree, but thinking about this type of problem more generally, it would be nice to know that there is a solution that doesn't involve that extra level of work (a nice tool for the pixel-polishing toolbox).

**Comment by jbphet** [comment] 2020-09-10 22:13
In response to the questions posed to me above, I'm using Chrome version 85.0.4183.102 (Official Build) (64-bit) for my browser and my external display resolution is 1920 x 1200 (and the settings app says that this is "recommended").

**Comment by zepumph** [comment] 2020-09-14 17:08
Thanks @jbphet, @amanda-phet would you mind giving us these icons with much better resolution (not sure exactly what that means), and we can put them in the sim and see if it fixes this?

**Comment by amanda-phet** [comment] 2020-09-16 22:29
Here they are at super high resolution! Also exported using anti-aliasing, so hopefully that helps. 

![Gridlines_Grid2](https://user-images.githubusercontent.com/7852916/93398903-a8f9f800-f839-11ea-84c3-3658bb0ff46a.png)
![Gridlines_NumberedGrid2](https://user-images.githubusercontent.com/7852916/93398904-a9928e80-f839-11ea-82b1-dcff89e5e2b6.png)


Alternatively, we could save these as SVG. Maybe try that?

[SVG gridlines.zip](https://github.com/phetsims/ratio-and-proportion/files/5235249/SVG.gridlines.zip)

**Comment by zepumph** [comment] 2020-09-21 17:30
When I plugged in the even larger PNG files, I felt like the problem (where the middle line was thinner) got even worse. From that I wondered if the cause of the issue was in fact how the sim was scaling down the images, and not about pixel resolution of the originals. 

In the code I saw that at the beginning of this issue, the icons (~200X200px) were being scaled by a `.2`, which leaves a lot of room for the browser to apply its own scaling criteria to the pixels. Using the SVGs above, I exported the icons in GIMP to be 50x50px, and the scale to make them the same size was `.84`. Comparing phettest to my local copy back and forth made me feel like the middle bar is more consistently wide now. @jbphet please review.


These don't really show any difference, I think the review should be done by looking at the sim.

Old image blown up:
![image](https://user-images.githubusercontent.com/6856943/93800286-d7d2ee00-fbec-11ea-88de-03c1e2bb3079.png)



Master blown up:
![image](https://user-images.githubusercontent.com/6856943/93800432-05b83280-fbed-11ea-95d5-9afd7a1dc57d.png)

**Comment by jbphet** [comment] 2020-09-28 15:50
They're definitely more consistent now.  A bit fuzzy, but equally so for all three lines.  I'll paste a screenshot from my external monitor below.  Honestly, if it were me, I think I'd take the time to create code-based nodes for them so that the crispness matched that of the eye icon (eye-con?), but it's up to @zepumph and @emily-phet whether that's worth the time.

![image](https://user-images.githubusercontent.com/3082831/94455116-f2b6dc80-016f-11eb-8720-9796bfe0e966.png)

**Comment by emily-phet** [comment] 2020-09-28 16:29
Now that pan/zoom is a thing (yay!) I think we'll need to do this in cases (like this) where the difference in crispness is noticeable.

**Comment by zepumph** [comment] 2020-09-28 18:45
When I open up the svgs from https://github.com/phetsims/ratio-and-proportion/issues/171#issuecomment-693699405, There isn't an obvious single shape, instead there a re a couple of shapes in `g` elements mixed with other elements (like `rect`). This will be quite manual and challenging to create, and I wonder if there is a way to export the SVG as a single "shape" or "vector" for the whole icon. That is what font awesome icons are like, like for the eye:

```
  eye_close: 'M555 201l78 141q-87 63 -136 159t-49 203q0 121 61 225q-229 -117 -381 -353q167 -258 427 -375zM944 960q0 20 -14 34t-34 14q-125 0 -214.5 -89.5t-89.5 -214.5q0 -20 14 -34t34 -14t34 14t14 34q0 86 61 147t147 61q20 0 34 14t14 34zM1307 1151q0 -7 -1 -9 q-105 -188 -315 -566t-316 -567l-49 -89q-10 -16 -28 -16q-12 0 -134 70q-16 10 -16 28q0 12 44 87q-143 65 -263.5 173t-208.5 245q-20 31 -20 69t20 69q153 235 380 371t496 136q89 0 180 -17l54 97q10 16 28 16q5 0 18 -6t31 -15.5t33 -18.5t31.5 -18.5t19.5 -11.5 q16 -10 16 -27zM1344 704q0 -139 -79 -253.5t-209 -164.5l280 502q8 -45 8 -84zM1792 576q0 -35 -20 -69q-39 -64 -109 -145q-150 -172 -347.5 -267t-419.5 -95l74 132q212 18 392.5 137t301.5 307q-115 179 -282 294l63 112q95 -64 182.5 -153t144.5 -184q20 -34 20 -69z',

```


Here is the numbered SVG as text:

```html
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.2.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
<g id="Layer_1">
</g>
<g id="Layer_1_copy">
	<g>
		<path d="M44.903,31.394l2.922-0.354c0.093,0.745,0.344,1.314,0.752,1.708c0.408,0.394,0.902,0.591,1.482,0.591
			c0.623,0,1.147-0.236,1.573-0.709c0.427-0.473,0.64-1.11,0.64-1.912c0-0.759-0.204-1.36-0.612-1.805
			c-0.408-0.444-0.906-0.666-1.493-0.666c-0.387,0-0.849,0.075-1.386,0.226l0.333-2.46c0.816,0.021,1.439-0.156,1.869-0.532
			s0.645-0.875,0.645-1.499c0-0.53-0.157-0.952-0.473-1.268c-0.315-0.315-0.734-0.473-1.257-0.473c-0.516,0-0.956,0.179-1.321,0.537
			c-0.365,0.358-0.587,0.881-0.666,1.568l-2.782-0.473c0.193-0.952,0.485-1.713,0.875-2.283c0.391-0.569,0.936-1.017,1.633-1.343
			c0.699-0.326,1.481-0.489,2.348-0.489c1.482,0,2.671,0.473,3.566,1.418c0.737,0.773,1.106,1.647,1.106,2.621
			c0,1.382-0.756,2.485-2.267,3.309c0.902,0.193,1.624,0.627,2.164,1.3c0.541,0.673,0.812,1.486,0.812,2.438
			c0,1.382-0.505,2.561-1.515,3.534c-1.01,0.974-2.267,1.461-3.771,1.461c-1.425,0-2.606-0.41-3.545-1.23
			C45.598,33.792,45.054,32.719,44.903,31.394z"/>
	</g>
	<g>
		<path d="M55.206,55.102v2.804H44.625c0.114-1.06,0.458-2.063,1.031-3.013s1.704-2.208,3.395-3.776
			c1.36-1.268,2.195-2.127,2.503-2.578c0.415-0.623,0.623-1.239,0.623-1.848c0-0.673-0.181-1.19-0.543-1.552
			c-0.361-0.361-0.86-0.542-1.498-0.542c-0.63,0-1.132,0.19-1.504,0.569c-0.372,0.38-0.587,1.01-0.645,1.891l-3.008-0.301
			c0.179-1.661,0.741-2.854,1.687-3.577c0.945-0.723,2.127-1.085,3.545-1.085c1.554,0,2.775,0.419,3.663,1.257
			s1.332,1.88,1.332,3.126c0,0.709-0.127,1.384-0.381,2.025c-0.255,0.641-0.657,1.312-1.209,2.014
			c-0.365,0.466-1.024,1.135-1.977,2.009c-0.952,0.874-1.556,1.454-1.811,1.74c-0.254,0.287-0.46,0.566-0.617,0.838H55.206z"/>
	</g>
	<g>
		<path d="M52.735,80.24h-3.019V68.864c-1.103,1.031-2.402,1.794-3.899,2.288v-2.739c0.788-0.258,1.644-0.747,2.567-1.467
			s1.558-1.559,1.901-2.519h2.449V80.24z"/>
	</g>
	<rect x="5.75" y="25.301" fill="#4D4D4D" width="34" height="5"/>
	<rect x="60.25" y="25.301" fill="#4D4D4D" width="34" height="5"/>
	<rect x="5.75" y="47.499" fill="#4D4D4D" width="34" height="5"/>
	<rect x="60.25" y="47.499" fill="#4D4D4D" width="34" height="5"/>
	<rect x="5.75" y="69.833" fill="#4D4D4D" width="34" height="5"/>
	<rect x="60.25" y="69.833" fill="#4D4D4D" width="34" height="5"/>
</g>
</svg>

```

**Comment by zepumph** [comment] 2020-09-28 18:48
When I open the SVG in inkscape, I can combine this into a path by:
* Select all
* Path -> Union
* Path -> Combine
* File -> Save as -> Optimized SVG

Then I end up with a single path with a `d` attribute I will use to create the shape.

**Comment by zepumph** [comment] 2020-09-28 19:56
After I convert the PNGs to `SCENERY/Path` using the above steps to export the SVGs to the correct format, here is the difference when zoomed in:

Before:
![image](https://user-images.githubusercontent.com/6856943/94478323-9956a980-017f-11eb-968d-d0b70bae91a6.png)

After: 
![image](https://user-images.githubusercontent.com/6856943/94478375-ab384c80-017f-11eb-9325-202f9d420924.png)

I know that this isn't the main problem, but a symptom caused by my bad fix above. No matter, I also can't reproduce the original problem from this issue.

@jbphet thanks for pushing me in the right direction. Please take another look on master.

**Comment by jbphet** [comment] 2020-09-29 16:18
Looks much better on master!

**Comment by zepumph** [comment] 2020-09-29 16:37
Excellent. I'm going to close this.

**Closed by zepumph** 2020-09-29 16:37 UTC
Labels: status:ready-for-review
