### ISSUE TITLE
Hands are unable to recognize subtle position changes when dealing with small ratios

### ISSUE THREAD

**Issue by DevonQui** [phetsims/ratio-and-proportion#275] opened 2020-12-08 23:18 UTC
**Test device**
MacBook Pro
**Operating System**
11.0.1 Big Sur
**Browser**
Safari
**Problem description**
This is for https://github.com/phetsims/QA/issues/582
When making a proportion of 10:1 (left-hand 10, right-hand 1) I noticed that the sim was unable to pick up on smaller values for a given ratio. For example, when moving the left-hand to 1, I should be able to put the right-hand somewhere around 0.1 to fulfill the ratio of 10:1 and hear the bell sound.  Instead, I can only get close to that value and will only hear the ticking sound no matter how slowly I move over that specific position. 
**Steps to reproduce**
1. Open the simulation
2.  Click on the Create section
3. Open My Challenge
4. Set the left-hand to 1 and the right-hand to a value greater 6
5. Turn on the number line at the right-hand corner and place the right-hand over 1
6. Try to move the left hand on top of the correct value to produce the bell sound (you shouldn't be able to)
**Visuals**
Here's a link to the video visual:
https://drive.google.com/file/d/1vzxdNzfXjTLBmyEFJOlV59tzX2e_dOjU/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.77/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-dev.77 2020-12-08 00:32:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
Language: en-us
Window: 1440x792
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by zepumph** [comment] 2020-12-09 02:01
@emily-phet please watch this video. The first case is below the "no success" threshold, and the second is above it.

@DevonQui et al, you can confirm this behavior by adding `?log` as a query parameter, and noting that when either value is below .021 in the model, then the "in proportion" state cannot be reached. 

This is a design consideration if we want to treat this as a problem.

**Comment by emily-phet** [comment] 2020-12-09 14:34
I believe this is happening because, at 0-30 gridlines view, having hands at 5 and 0.5 is the equivalent of having a left-hand value of 1.5 and .15 in the 0-10 gridlines view. Below 0.21 in the 0-10 gridlines view does not result in being "in ratio" so this expected. 

We could decrease the threshold below 0.21 to address this (to 0.14), but I'm not sure what the full impact of that would be.

@BLFiedler and @terracoda - thoughts on setting the threshold at 0.14 vs leaving it at 0.21?

**Comment by terracoda** [comment] 2020-12-09 20:33
I am ok with this change.
Can we verify that the described positions of 0.14 is "near bottom" and "near tick mark zero"?

And then, 1:2 could be
0.14:0.28

Can we also verify that the described positions of 0.28, assuming that is a 1:2 ratio, would 0.28 for the right hand be "near bottom", "around half-way to first tick mark", and "around tick mark 0.5"?

The position descriptions near the bottom are often not different, or at least not very distinguishable.

**Comment by terracoda** [comment] 2020-12-10 15:05
Addressing this issue may be helpful for #279 and #209. 
I think it is important to keep in mind the Tick Mark Range 0 to 30.

And regarding my previous comment https://github.com/phetsims/ratio-and-proportion/issues/275#issuecomment-742031683, I think it is ok that when we are down near the bottom the position and distance descriptions are fuzzy and not so different from each other. It is the same for the visuals.

I think it would be nice, if in all Tick Mark Ranges, we can get the Left hand on the first. I don't know if this is possible, but it seems important to be able to start at 0 or 1 and move up from there.

**Comment by terracoda** [comment] 2020-12-10 15:10
When I explored the example 10:1, I am pretty sure this issue is related to #279. The Left hand is not landing on the even tick marks properly. I could be wrong, but that's my guess.

Un-assigning myself for now. please let me know if I need to comment more.

**Comment by BLFiedler** [comment] 2020-12-10 15:30
I'll just remark that part of the original purpose for the hollywood zone was to prevent users from mistaking the hand position as being "the same" (and thus 1:1) and ascertaining that possibly 1) the ratio differs depending on where on the screen you are, or 2) you can only get the ratio near the bottom and not exploring the rest of the screen. This was a problem near the bottom of the screen where there is very little difference in the distance between the hands. 

That being said, with the bigger hand sizes and other changes we have made visually, if 0.14 still looks spatially separated to others, than I have no problem. Right now the hand is snapping to zero when I get close, so it's a little hard to tell. Is this a new feature?

**Comment by zepumph** [comment] 2020-12-15 19:17
To help remedy this weirdness, especially in correlatyion with https://github.com/phetsims/ratio-and-proportion/issues/288, @BLFiedler, @terracoda, @Matthew-Moore240, and @zepumph think that we should do the following:

* Lower the hollywood, no-success range to .1 exclusive of a tick mark
* Change the snap behavior to snap within .1 of a tick mark (exclusive).

@terracoda is excited about this because she feels like it will fix a lot of the problems she has been encountering when using the sim with description for smaller values.

**Comment by zepumph** [comment] 2020-12-15 20:11
@BLFiedler, we didn't discuss today that the snapping behavior in general (including to zero) doesn't happen when range is not 0-10. Do we need to add that to make this work? Or is the important bit that we decreased the hollywood, no-success zone.

**Comment by BLFiedler** [comment] 2020-12-15 20:29
I believe the only needed outcome is that we lower the no-success zone upper threshold and align its value to the grid used in alt input/description. The change to the snapping value is just another case of aligning to the grid (as it was a value inaccessible to alt input), but not technically crucial to this issue.

**Comment by zepumph** [comment] 2020-12-15 22:59
Sounds good. What more do we need for this issue?

**Comment by terracoda** [comment] 2020-12-17 13:49
@zepumph, could you please describe what this means in real shift-key-measured terms.

For example, should I be able to move left hand up 1 shift key press from zero and the right hand up 2 shift key presses from zero and get challenge ratio with Challenge 1 (1:2)?

Currently, on Master (local PhET Marks after a fresh pull), I need to move left hand up 2 shift-key steps and right hand up 4 shift-key steps to get challenge ratio. 

After setting the hands with the keyboard to 2 steps: 4 steps, I can move the hands down a little more (with the mouse) and get a challenge ratio ding at a slightly lower position. I can't get to this lower position with small shift-key key presses. Is that the intended behaviour? Or should I also be able to get the challenge ding with shift-key key presses with 1 step: 2 steps.

Note: I was testing on screen 2, the Create Screen. 

While testing this issue, I noticed a slight discrepancy in shift-key step size when using Shift + W when using Both Hands. I'll open a new issue for that. The discrepancy might be a little random (not sure). It might also have to do with intended or unintended snapping behaviour (again not sure).

For this issue, @zepumph I am wondering what is the lowest position where I should be able to get to the challenge ratio when using shift-key key presses.

**Comment by zepumph** [comment] 2021-01-05 21:18
Today during a design meeting, @terracoda, @emily-phet, @BLFiedler and I confirmed that this behavior in https://github.com/phetsims/ratio-and-proportion/commit/bf94ff2c2e34761c9bf228900e59ed40b526d882 makes sense, and aligning the interactions (keyboard/mouse), while decreasing the hollywood zone is the way to go.

Part of the rationale for this late-stage change is that the original hollywood zone was largely designed around the continuous interaction space, and not so much about it being also a discrete interaction (keyboard). We are ready to close this.

**Closed by zepumph** 2021-01-05 21:18 UTC
Labels: status:blocks-sim-publication, status:ready-for-review, type:bug
